// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AudioFocusStateEnum.proto
// Protobuf C++ Version: 6.31.0

#ifndef AudioFocusStateEnum_2eproto_2epb_2eh
#define AudioFocusStateEnum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AudioFocusStateEnum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_AudioFocusStateEnum_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_AudioFocusStateEnum_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace enums {
enum AudioFocusState_Enum : int;
extern const uint32_t AudioFocusState_Enum_internal_data_[];
class AudioFocusState;
struct AudioFocusStateDefaultTypeInternal;
extern AudioFocusStateDefaultTypeInternal _AudioFocusState_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AudioFocusState_class_data_;
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::aasdk::proto::enums::AudioFocusState_Enum_internal_data_>
    internal::EnumTraitsImpl::value<::aasdk::proto::enums::AudioFocusState_Enum>;
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace enums {
enum AudioFocusState_Enum : int {
  AudioFocusState_Enum_NONE = 0,
  AudioFocusState_Enum_GAIN = 1,
  AudioFocusState_Enum_GAIN_TRANSIENT = 2,
  AudioFocusState_Enum_LOSS = 3,
  AudioFocusState_Enum_LOSS_TRANSIENT_CAN_DUCK = 4,
  AudioFocusState_Enum_LOSS_TRANSIENT = 5,
  AudioFocusState_Enum_GAIN_MEDIA_ONLY = 6,
  AudioFocusState_Enum_GAIN_TRANSIENT_GUIDANCE_ONLY = 7,
};

extern const uint32_t AudioFocusState_Enum_internal_data_[];
inline constexpr AudioFocusState_Enum AudioFocusState_Enum_Enum_MIN =
    static_cast<AudioFocusState_Enum>(0);
inline constexpr AudioFocusState_Enum AudioFocusState_Enum_Enum_MAX =
    static_cast<AudioFocusState_Enum>(7);
inline bool AudioFocusState_Enum_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int AudioFocusState_Enum_Enum_ARRAYSIZE = 7 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AudioFocusState_Enum_descriptor();
template <typename T>
const ::std::string& AudioFocusState_Enum_Name(T value) {
  static_assert(::std::is_same<T, AudioFocusState_Enum>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Enum_Name().");
  return AudioFocusState_Enum_Name(static_cast<AudioFocusState_Enum>(value));
}
template <>
inline const ::std::string& AudioFocusState_Enum_Name(AudioFocusState_Enum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AudioFocusState_Enum_descriptor, 0, 7>(
      static_cast<int>(value));
}
inline bool AudioFocusState_Enum_Parse(
    ::absl::string_view name, AudioFocusState_Enum* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<AudioFocusState_Enum>(AudioFocusState_Enum_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class AudioFocusState final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:aasdk.proto.enums.AudioFocusState) */ {
 public:
  inline AudioFocusState() : AudioFocusState(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AudioFocusState* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AudioFocusState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AudioFocusState(::google::protobuf::internal::ConstantInitialized);

  inline AudioFocusState(const AudioFocusState& from) : AudioFocusState(nullptr, from) {}
  inline AudioFocusState(AudioFocusState&& from) noexcept
      : AudioFocusState(nullptr, ::std::move(from)) {}
  inline AudioFocusState& operator=(const AudioFocusState& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudioFocusState& operator=(AudioFocusState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AudioFocusState& default_instance() {
    return *reinterpret_cast<const AudioFocusState*>(
        &_AudioFocusState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AudioFocusState& a, AudioFocusState& b) { a.Swap(&b); }
  inline void Swap(AudioFocusState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AudioFocusState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AudioFocusState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<AudioFocusState>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const AudioFocusState& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const AudioFocusState& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.enums.AudioFocusState"; }

 protected:
  explicit AudioFocusState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AudioFocusState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AudioFocusState& from);
  AudioFocusState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AudioFocusState&& from) noexcept
      : AudioFocusState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Enum = AudioFocusState_Enum;
  static constexpr Enum NONE = AudioFocusState_Enum_NONE;
  static constexpr Enum GAIN = AudioFocusState_Enum_GAIN;
  static constexpr Enum GAIN_TRANSIENT = AudioFocusState_Enum_GAIN_TRANSIENT;
  static constexpr Enum LOSS = AudioFocusState_Enum_LOSS;
  static constexpr Enum LOSS_TRANSIENT_CAN_DUCK = AudioFocusState_Enum_LOSS_TRANSIENT_CAN_DUCK;
  static constexpr Enum LOSS_TRANSIENT = AudioFocusState_Enum_LOSS_TRANSIENT;
  static constexpr Enum GAIN_MEDIA_ONLY = AudioFocusState_Enum_GAIN_MEDIA_ONLY;
  static constexpr Enum GAIN_TRANSIENT_GUIDANCE_ONLY = AudioFocusState_Enum_GAIN_TRANSIENT_GUIDANCE_ONLY;
  static inline bool Enum_IsValid(int value) {
    return AudioFocusState_Enum_IsValid(value);
  }
  static constexpr Enum Enum_MIN = AudioFocusState_Enum_Enum_MIN;
  static constexpr Enum Enum_MAX = AudioFocusState_Enum_Enum_MAX;
  static constexpr int Enum_ARRAYSIZE = AudioFocusState_Enum_Enum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Enum_descriptor() {
    return AudioFocusState_Enum_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Enum_Name(T value) {
    return AudioFocusState_Enum_Name(value);
  }
  static inline bool Enum_Parse(
      ::absl::string_view name, Enum* PROTOBUF_NONNULL value) {
    return AudioFocusState_Enum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:aasdk.proto.enums.AudioFocusState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AudioFocusState& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_AudioFocusStateEnum_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AudioFocusState_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AudioFocusState

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace enums
}  // namespace proto
}  // namespace aasdk


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::aasdk::proto::enums::AudioFocusState_Enum> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::aasdk::proto::enums::AudioFocusState_Enum>() {
  return ::aasdk::proto::enums::AudioFocusState_Enum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // AudioFocusStateEnum_2eproto_2epb_2eh
