// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AVInputOpenResponseMessage.proto
// Protobuf C++ Version: 6.31.0

#include "AVInputOpenResponseMessage.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace messages {

inline constexpr AVInputOpenResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        session_{0},
        value_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR AVInputOpenResponse::AVInputOpenResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AVInputOpenResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AVInputOpenResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AVInputOpenResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AVInputOpenResponseDefaultTypeInternal() {}
  union {
    AVInputOpenResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AVInputOpenResponseDefaultTypeInternal _AVInputOpenResponse_default_instance_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_AVInputOpenResponseMessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_AVInputOpenResponseMessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_AVInputOpenResponseMessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::AVInputOpenResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::AVInputOpenResponse, _impl_.session_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::AVInputOpenResponse, _impl_.value_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::messages::AVInputOpenResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::messages::_AVInputOpenResponse_default_instance_._instance,
};
const char descriptor_table_protodef_AVInputOpenResponseMessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n AVInputOpenResponseMessage.proto\022\024aasd"
    "k.proto.messages\"5\n\023AVInputOpenResponse\022"
    "\017\n\007session\030\001 \002(\005\022\r\n\005value\030\002 \002(\r"
};
static ::absl::once_flag descriptor_table_AVInputOpenResponseMessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_AVInputOpenResponseMessage_2eproto = {
    false,
    false,
    111,
    descriptor_table_protodef_AVInputOpenResponseMessage_2eproto,
    "AVInputOpenResponseMessage.proto",
    &descriptor_table_AVInputOpenResponseMessage_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_AVInputOpenResponseMessage_2eproto::offsets,
    file_level_enum_descriptors_AVInputOpenResponseMessage_2eproto,
    file_level_service_descriptors_AVInputOpenResponseMessage_2eproto,
};
namespace aasdk {
namespace proto {
namespace messages {
// ===================================================================

class AVInputOpenResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AVInputOpenResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

AVInputOpenResponse::AVInputOpenResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AVInputOpenResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.messages.AVInputOpenResponse)
}
AVInputOpenResponse::AVInputOpenResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AVInputOpenResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AVInputOpenResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE AVInputOpenResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void AVInputOpenResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, session_),
           0,
           offsetof(Impl_, value_) -
               offsetof(Impl_, session_) +
               sizeof(Impl_::value_));
}
AVInputOpenResponse::~AVInputOpenResponse() {
  // @@protoc_insertion_point(destructor:aasdk.proto.messages.AVInputOpenResponse)
  SharedDtor(*this);
}
inline void AVInputOpenResponse::SharedDtor(MessageLite& self) {
  AVInputOpenResponse& this_ = static_cast<AVInputOpenResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AVInputOpenResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AVInputOpenResponse(arena);
}
constexpr auto AVInputOpenResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AVInputOpenResponse),
                                            alignof(AVInputOpenResponse));
}
constexpr auto AVInputOpenResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AVInputOpenResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          AVInputOpenResponse::IsInitializedImpl,
          &AVInputOpenResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AVInputOpenResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AVInputOpenResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AVInputOpenResponse>(), &AVInputOpenResponse::ByteSizeLong,
              &AVInputOpenResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_._cached_size_),
          false,
      },
      &AVInputOpenResponse::kDescriptorMethods,
      &descriptor_table_AVInputOpenResponseMessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AVInputOpenResponse_class_data_ =
        AVInputOpenResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AVInputOpenResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AVInputOpenResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AVInputOpenResponse_class_data_.tc_table);
  return AVInputOpenResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
AVInputOpenResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AVInputOpenResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::messages::AVInputOpenResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required uint32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AVInputOpenResponse, _impl_.value_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_.value_)}},
    // required int32 session = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AVInputOpenResponse, _impl_.session_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_.session_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 session = 1;
    {PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_.session_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required uint32 value = 2;
    {PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void AVInputOpenResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.messages.AVInputOpenResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.session_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.value_) -
        reinterpret_cast<char*>(&_impl_.session_)) + sizeof(_impl_.value_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AVInputOpenResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AVInputOpenResponse& this_ = static_cast<const AVInputOpenResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AVInputOpenResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AVInputOpenResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.messages.AVInputOpenResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required int32 session = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_session(), target);
  }

  // required uint32 value = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_value(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.messages.AVInputOpenResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AVInputOpenResponse::ByteSizeLong(const MessageLite& base) {
  const AVInputOpenResponse& this_ = static_cast<const AVInputOpenResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AVInputOpenResponse::ByteSizeLong() const {
  const AVInputOpenResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aasdk.proto.messages.AVInputOpenResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // required int32 session = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_session());
    }
    // required uint32 value = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_value());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AVInputOpenResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AVInputOpenResponse*>(&to_msg);
  auto& from = static_cast<const AVInputOpenResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.messages.AVInputOpenResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.session_ = from._impl_.session_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.value_ = from._impl_.value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AVInputOpenResponse::CopyFrom(const AVInputOpenResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.messages.AVInputOpenResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AVInputOpenResponse::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const AVInputOpenResponse&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void AVInputOpenResponse::InternalSwap(AVInputOpenResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_.value_)
      + sizeof(AVInputOpenResponse::_impl_.value_)
      - PROTOBUF_FIELD_OFFSET(AVInputOpenResponse, _impl_.session_)>(
          reinterpret_cast<char*>(&_impl_.session_),
          reinterpret_cast<char*>(&other->_impl_.session_));
}

::google::protobuf::Metadata AVInputOpenResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_AVInputOpenResponseMessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
