// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ChannelDescriptorData.proto
// Protobuf C++ Version: 6.31.0

#ifndef ChannelDescriptorData_2eproto_2epb_2eh
#define ChannelDescriptorData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "SensorChannelData.pb.h"
#include "AVChannelData.pb.h"
#include "InputChannelData.pb.h"
#include "AVInputChannelData.pb.h"
#include "BluetoothChannelData.pb.h"
#include "NavigationChannelData.pb.h"
#include "VendorExtensionChannelData.pb.h"
#include "MediaInfoChannelData.pb.h"
#include "WifiChannelData.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ChannelDescriptorData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ChannelDescriptorData_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ChannelDescriptorData_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace data {
class ChannelDescriptor;
struct ChannelDescriptorDefaultTypeInternal;
extern ChannelDescriptorDefaultTypeInternal _ChannelDescriptor_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ChannelDescriptor_class_data_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace data {

// ===================================================================


// -------------------------------------------------------------------

class ChannelDescriptor final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aasdk.proto.data.ChannelDescriptor) */ {
 public:
  inline ChannelDescriptor() : ChannelDescriptor(nullptr) {}
  ~ChannelDescriptor() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ChannelDescriptor* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ChannelDescriptor));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ChannelDescriptor(::google::protobuf::internal::ConstantInitialized);

  inline ChannelDescriptor(const ChannelDescriptor& from) : ChannelDescriptor(nullptr, from) {}
  inline ChannelDescriptor(ChannelDescriptor&& from) noexcept
      : ChannelDescriptor(nullptr, ::std::move(from)) {}
  inline ChannelDescriptor& operator=(const ChannelDescriptor& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChannelDescriptor& operator=(ChannelDescriptor&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChannelDescriptor& default_instance() {
    return *reinterpret_cast<const ChannelDescriptor*>(
        &_ChannelDescriptor_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ChannelDescriptor& a, ChannelDescriptor& b) { a.Swap(&b); }
  inline void Swap(ChannelDescriptor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChannelDescriptor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChannelDescriptor* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ChannelDescriptor>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ChannelDescriptor& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ChannelDescriptor& from) { ChannelDescriptor::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ChannelDescriptor* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.data.ChannelDescriptor"; }

 protected:
  explicit ChannelDescriptor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ChannelDescriptor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ChannelDescriptor& from);
  ChannelDescriptor(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ChannelDescriptor&& from) noexcept
      : ChannelDescriptor(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSensorChannelFieldNumber = 2,
    kAvChannelFieldNumber = 3,
    kInputChannelFieldNumber = 4,
    kAvInputChannelFieldNumber = 5,
    kBluetoothChannelFieldNumber = 6,
    kNavigationChannelFieldNumber = 8,
    kMediaInfoChannelFieldNumber = 9,
    kVendorExtensionChannelFieldNumber = 12,
    kWifiChannelFieldNumber = 16,
    kChannelIdFieldNumber = 1,
  };
  // optional .aasdk.proto.data.SensorChannel sensor_channel = 2;
  bool has_sensor_channel() const;
  void clear_sensor_channel() ;
  const ::aasdk::proto::data::SensorChannel& sensor_channel() const;
  [[nodiscard]] ::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE release_sensor_channel();
  ::aasdk::proto::data::SensorChannel* PROTOBUF_NONNULL mutable_sensor_channel();
  void set_allocated_sensor_channel(::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_sensor_channel(::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE unsafe_arena_release_sensor_channel();

  private:
  const ::aasdk::proto::data::SensorChannel& _internal_sensor_channel() const;
  ::aasdk::proto::data::SensorChannel* PROTOBUF_NONNULL _internal_mutable_sensor_channel();

  public:
  // optional .aasdk.proto.data.AVChannel av_channel = 3;
  bool has_av_channel() const;
  void clear_av_channel() ;
  const ::aasdk::proto::data::AVChannel& av_channel() const;
  [[nodiscard]] ::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE release_av_channel();
  ::aasdk::proto::data::AVChannel* PROTOBUF_NONNULL mutable_av_channel();
  void set_allocated_av_channel(::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_av_channel(::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE unsafe_arena_release_av_channel();

  private:
  const ::aasdk::proto::data::AVChannel& _internal_av_channel() const;
  ::aasdk::proto::data::AVChannel* PROTOBUF_NONNULL _internal_mutable_av_channel();

  public:
  // optional .aasdk.proto.data.InputChannel input_channel = 4;
  bool has_input_channel() const;
  void clear_input_channel() ;
  const ::aasdk::proto::data::InputChannel& input_channel() const;
  [[nodiscard]] ::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE release_input_channel();
  ::aasdk::proto::data::InputChannel* PROTOBUF_NONNULL mutable_input_channel();
  void set_allocated_input_channel(::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_input_channel(::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE unsafe_arena_release_input_channel();

  private:
  const ::aasdk::proto::data::InputChannel& _internal_input_channel() const;
  ::aasdk::proto::data::InputChannel* PROTOBUF_NONNULL _internal_mutable_input_channel();

  public:
  // optional .aasdk.proto.data.AVInputChannel av_input_channel = 5;
  bool has_av_input_channel() const;
  void clear_av_input_channel() ;
  const ::aasdk::proto::data::AVInputChannel& av_input_channel() const;
  [[nodiscard]] ::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE release_av_input_channel();
  ::aasdk::proto::data::AVInputChannel* PROTOBUF_NONNULL mutable_av_input_channel();
  void set_allocated_av_input_channel(::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_av_input_channel(::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE unsafe_arena_release_av_input_channel();

  private:
  const ::aasdk::proto::data::AVInputChannel& _internal_av_input_channel() const;
  ::aasdk::proto::data::AVInputChannel* PROTOBUF_NONNULL _internal_mutable_av_input_channel();

  public:
  // optional .aasdk.proto.data.BluetoothChannel bluetooth_channel = 6;
  bool has_bluetooth_channel() const;
  void clear_bluetooth_channel() ;
  const ::aasdk::proto::data::BluetoothChannel& bluetooth_channel() const;
  [[nodiscard]] ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE release_bluetooth_channel();
  ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NONNULL mutable_bluetooth_channel();
  void set_allocated_bluetooth_channel(::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_bluetooth_channel(::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE unsafe_arena_release_bluetooth_channel();

  private:
  const ::aasdk::proto::data::BluetoothChannel& _internal_bluetooth_channel() const;
  ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NONNULL _internal_mutable_bluetooth_channel();

  public:
  // optional .aasdk.proto.data.NavigationChannel navigation_channel = 8;
  bool has_navigation_channel() const;
  void clear_navigation_channel() ;
  const ::aasdk::proto::data::NavigationChannel& navigation_channel() const;
  [[nodiscard]] ::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE release_navigation_channel();
  ::aasdk::proto::data::NavigationChannel* PROTOBUF_NONNULL mutable_navigation_channel();
  void set_allocated_navigation_channel(::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_navigation_channel(::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE unsafe_arena_release_navigation_channel();

  private:
  const ::aasdk::proto::data::NavigationChannel& _internal_navigation_channel() const;
  ::aasdk::proto::data::NavigationChannel* PROTOBUF_NONNULL _internal_mutable_navigation_channel();

  public:
  // optional .aasdk.proto.data.MediaInfoChannel media_infoChannel = 9;
  bool has_media_infochannel() const;
  void clear_media_infochannel() ;
  const ::aasdk::proto::data::MediaInfoChannel& media_infochannel() const;
  [[nodiscard]] ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE release_media_infochannel();
  ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NONNULL mutable_media_infochannel();
  void set_allocated_media_infochannel(::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_media_infochannel(::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE unsafe_arena_release_media_infochannel();

  private:
  const ::aasdk::proto::data::MediaInfoChannel& _internal_media_infochannel() const;
  ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NONNULL _internal_mutable_media_infochannel();

  public:
  // optional .aasdk.proto.data.VendorExtensionChannel vendor_extension_channel = 12;
  bool has_vendor_extension_channel() const;
  void clear_vendor_extension_channel() ;
  const ::aasdk::proto::data::VendorExtensionChannel& vendor_extension_channel() const;
  [[nodiscard]] ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE release_vendor_extension_channel();
  ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NONNULL mutable_vendor_extension_channel();
  void set_allocated_vendor_extension_channel(::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_vendor_extension_channel(::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE unsafe_arena_release_vendor_extension_channel();

  private:
  const ::aasdk::proto::data::VendorExtensionChannel& _internal_vendor_extension_channel() const;
  ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NONNULL _internal_mutable_vendor_extension_channel();

  public:
  // optional .aasdk.proto.data.WifiChannel wifi_channel = 16;
  bool has_wifi_channel() const;
  void clear_wifi_channel() ;
  const ::aasdk::proto::data::WifiChannel& wifi_channel() const;
  [[nodiscard]] ::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE release_wifi_channel();
  ::aasdk::proto::data::WifiChannel* PROTOBUF_NONNULL mutable_wifi_channel();
  void set_allocated_wifi_channel(::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_wifi_channel(::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE value);
  ::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE unsafe_arena_release_wifi_channel();

  private:
  const ::aasdk::proto::data::WifiChannel& _internal_wifi_channel() const;
  ::aasdk::proto::data::WifiChannel* PROTOBUF_NONNULL _internal_mutable_wifi_channel();

  public:
  // required uint32 channel_id = 1;
  bool has_channel_id() const;
  void clear_channel_id() ;
  ::uint32_t channel_id() const;
  void set_channel_id(::uint32_t value);

  private:
  ::uint32_t _internal_channel_id() const;
  void _internal_set_channel_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:aasdk.proto.data.ChannelDescriptor)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   9, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ChannelDescriptor& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE sensor_channel_;
    ::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE av_channel_;
    ::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE input_channel_;
    ::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE av_input_channel_;
    ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE bluetooth_channel_;
    ::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE navigation_channel_;
    ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE media_infochannel_;
    ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE vendor_extension_channel_;
    ::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE wifi_channel_;
    ::uint32_t channel_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ChannelDescriptorData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ChannelDescriptor_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ChannelDescriptor

// required uint32 channel_id = 1;
inline bool ChannelDescriptor::has_channel_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void ChannelDescriptor::clear_channel_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channel_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline ::uint32_t ChannelDescriptor::channel_id() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.channel_id)
  return _internal_channel_id();
}
inline void ChannelDescriptor::set_channel_id(::uint32_t value) {
  _internal_set_channel_id(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:aasdk.proto.data.ChannelDescriptor.channel_id)
}
inline ::uint32_t ChannelDescriptor::_internal_channel_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.channel_id_;
}
inline void ChannelDescriptor::_internal_set_channel_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channel_id_ = value;
}

// optional .aasdk.proto.data.SensorChannel sensor_channel = 2;
inline bool ChannelDescriptor::has_sensor_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.sensor_channel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::SensorChannel& ChannelDescriptor::_internal_sensor_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::SensorChannel* p = _impl_.sensor_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::SensorChannel&>(::aasdk::proto::data::_SensorChannel_default_instance_);
}
inline const ::aasdk::proto::data::SensorChannel& ChannelDescriptor::sensor_channel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.sensor_channel)
  return _internal_sensor_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_sensor_channel(
    ::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.sensor_channel_);
  }
  _impl_.sensor_channel_ = reinterpret_cast<::aasdk::proto::data::SensorChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.sensor_channel)
}
inline ::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_sensor_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::aasdk::proto::data::SensorChannel* released = _impl_.sensor_channel_;
  _impl_.sensor_channel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_sensor_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.sensor_channel)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::aasdk::proto::data::SensorChannel* temp = _impl_.sensor_channel_;
  _impl_.sensor_channel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::SensorChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_sensor_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.sensor_channel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::SensorChannel>(GetArena());
    _impl_.sensor_channel_ = reinterpret_cast<::aasdk::proto::data::SensorChannel*>(p);
  }
  return _impl_.sensor_channel_;
}
inline ::aasdk::proto::data::SensorChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_sensor_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::aasdk::proto::data::SensorChannel* _msg = _internal_mutable_sensor_channel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.sensor_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_sensor_channel(::aasdk::proto::data::SensorChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.sensor_channel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.sensor_channel_ = reinterpret_cast<::aasdk::proto::data::SensorChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.sensor_channel)
}

// optional .aasdk.proto.data.AVChannel av_channel = 3;
inline bool ChannelDescriptor::has_av_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.av_channel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::AVChannel& ChannelDescriptor::_internal_av_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::AVChannel* p = _impl_.av_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::AVChannel&>(::aasdk::proto::data::_AVChannel_default_instance_);
}
inline const ::aasdk::proto::data::AVChannel& ChannelDescriptor::av_channel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.av_channel)
  return _internal_av_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_av_channel(
    ::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.av_channel_);
  }
  _impl_.av_channel_ = reinterpret_cast<::aasdk::proto::data::AVChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.av_channel)
}
inline ::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_av_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::aasdk::proto::data::AVChannel* released = _impl_.av_channel_;
  _impl_.av_channel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_av_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.av_channel)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::aasdk::proto::data::AVChannel* temp = _impl_.av_channel_;
  _impl_.av_channel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::AVChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_av_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.av_channel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::AVChannel>(GetArena());
    _impl_.av_channel_ = reinterpret_cast<::aasdk::proto::data::AVChannel*>(p);
  }
  return _impl_.av_channel_;
}
inline ::aasdk::proto::data::AVChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_av_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::aasdk::proto::data::AVChannel* _msg = _internal_mutable_av_channel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.av_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_av_channel(::aasdk::proto::data::AVChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.av_channel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.av_channel_ = reinterpret_cast<::aasdk::proto::data::AVChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.av_channel)
}

// optional .aasdk.proto.data.InputChannel input_channel = 4;
inline bool ChannelDescriptor::has_input_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.input_channel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::InputChannel& ChannelDescriptor::_internal_input_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::InputChannel* p = _impl_.input_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::InputChannel&>(::aasdk::proto::data::_InputChannel_default_instance_);
}
inline const ::aasdk::proto::data::InputChannel& ChannelDescriptor::input_channel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.input_channel)
  return _internal_input_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_input_channel(
    ::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.input_channel_);
  }
  _impl_.input_channel_ = reinterpret_cast<::aasdk::proto::data::InputChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.input_channel)
}
inline ::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_input_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::aasdk::proto::data::InputChannel* released = _impl_.input_channel_;
  _impl_.input_channel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_input_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.input_channel)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::aasdk::proto::data::InputChannel* temp = _impl_.input_channel_;
  _impl_.input_channel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::InputChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_input_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.input_channel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::InputChannel>(GetArena());
    _impl_.input_channel_ = reinterpret_cast<::aasdk::proto::data::InputChannel*>(p);
  }
  return _impl_.input_channel_;
}
inline ::aasdk::proto::data::InputChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_input_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::aasdk::proto::data::InputChannel* _msg = _internal_mutable_input_channel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.input_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_input_channel(::aasdk::proto::data::InputChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.input_channel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.input_channel_ = reinterpret_cast<::aasdk::proto::data::InputChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.input_channel)
}

// optional .aasdk.proto.data.AVInputChannel av_input_channel = 5;
inline bool ChannelDescriptor::has_av_input_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.av_input_channel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::AVInputChannel& ChannelDescriptor::_internal_av_input_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::AVInputChannel* p = _impl_.av_input_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::AVInputChannel&>(::aasdk::proto::data::_AVInputChannel_default_instance_);
}
inline const ::aasdk::proto::data::AVInputChannel& ChannelDescriptor::av_input_channel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.av_input_channel)
  return _internal_av_input_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_av_input_channel(
    ::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.av_input_channel_);
  }
  _impl_.av_input_channel_ = reinterpret_cast<::aasdk::proto::data::AVInputChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.av_input_channel)
}
inline ::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_av_input_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::aasdk::proto::data::AVInputChannel* released = _impl_.av_input_channel_;
  _impl_.av_input_channel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_av_input_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.av_input_channel)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::aasdk::proto::data::AVInputChannel* temp = _impl_.av_input_channel_;
  _impl_.av_input_channel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::AVInputChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_av_input_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.av_input_channel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::AVInputChannel>(GetArena());
    _impl_.av_input_channel_ = reinterpret_cast<::aasdk::proto::data::AVInputChannel*>(p);
  }
  return _impl_.av_input_channel_;
}
inline ::aasdk::proto::data::AVInputChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_av_input_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::aasdk::proto::data::AVInputChannel* _msg = _internal_mutable_av_input_channel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.av_input_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_av_input_channel(::aasdk::proto::data::AVInputChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.av_input_channel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.av_input_channel_ = reinterpret_cast<::aasdk::proto::data::AVInputChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.av_input_channel)
}

// optional .aasdk.proto.data.BluetoothChannel bluetooth_channel = 6;
inline bool ChannelDescriptor::has_bluetooth_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.bluetooth_channel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::BluetoothChannel& ChannelDescriptor::_internal_bluetooth_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::BluetoothChannel* p = _impl_.bluetooth_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::BluetoothChannel&>(::aasdk::proto::data::_BluetoothChannel_default_instance_);
}
inline const ::aasdk::proto::data::BluetoothChannel& ChannelDescriptor::bluetooth_channel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
  return _internal_bluetooth_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_bluetooth_channel(
    ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.bluetooth_channel_);
  }
  _impl_.bluetooth_channel_ = reinterpret_cast<::aasdk::proto::data::BluetoothChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
}
inline ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_bluetooth_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::aasdk::proto::data::BluetoothChannel* released = _impl_.bluetooth_channel_;
  _impl_.bluetooth_channel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_bluetooth_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.bluetooth_channel)

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::aasdk::proto::data::BluetoothChannel* temp = _impl_.bluetooth_channel_;
  _impl_.bluetooth_channel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_bluetooth_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.bluetooth_channel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::BluetoothChannel>(GetArena());
    _impl_.bluetooth_channel_ = reinterpret_cast<::aasdk::proto::data::BluetoothChannel*>(p);
  }
  return _impl_.bluetooth_channel_;
}
inline ::aasdk::proto::data::BluetoothChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_bluetooth_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000010u;
  ::aasdk::proto::data::BluetoothChannel* _msg = _internal_mutable_bluetooth_channel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_bluetooth_channel(::aasdk::proto::data::BluetoothChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.bluetooth_channel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }

  _impl_.bluetooth_channel_ = reinterpret_cast<::aasdk::proto::data::BluetoothChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
}

// optional .aasdk.proto.data.NavigationChannel navigation_channel = 8;
inline bool ChannelDescriptor::has_navigation_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.navigation_channel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::NavigationChannel& ChannelDescriptor::_internal_navigation_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::NavigationChannel* p = _impl_.navigation_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::NavigationChannel&>(::aasdk::proto::data::_NavigationChannel_default_instance_);
}
inline const ::aasdk::proto::data::NavigationChannel& ChannelDescriptor::navigation_channel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.navigation_channel)
  return _internal_navigation_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_navigation_channel(
    ::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.navigation_channel_);
  }
  _impl_.navigation_channel_ = reinterpret_cast<::aasdk::proto::data::NavigationChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.navigation_channel)
}
inline ::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_navigation_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000020u;
  ::aasdk::proto::data::NavigationChannel* released = _impl_.navigation_channel_;
  _impl_.navigation_channel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_navigation_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.navigation_channel)

  _impl_._has_bits_[0] &= ~0x00000020u;
  ::aasdk::proto::data::NavigationChannel* temp = _impl_.navigation_channel_;
  _impl_.navigation_channel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::NavigationChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_navigation_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.navigation_channel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::NavigationChannel>(GetArena());
    _impl_.navigation_channel_ = reinterpret_cast<::aasdk::proto::data::NavigationChannel*>(p);
  }
  return _impl_.navigation_channel_;
}
inline ::aasdk::proto::data::NavigationChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_navigation_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000020u;
  ::aasdk::proto::data::NavigationChannel* _msg = _internal_mutable_navigation_channel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.navigation_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_navigation_channel(::aasdk::proto::data::NavigationChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.navigation_channel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }

  _impl_.navigation_channel_ = reinterpret_cast<::aasdk::proto::data::NavigationChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.navigation_channel)
}

// optional .aasdk.proto.data.MediaInfoChannel media_infoChannel = 9;
inline bool ChannelDescriptor::has_media_infochannel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.media_infochannel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::MediaInfoChannel& ChannelDescriptor::_internal_media_infochannel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::MediaInfoChannel* p = _impl_.media_infochannel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::MediaInfoChannel&>(::aasdk::proto::data::_MediaInfoChannel_default_instance_);
}
inline const ::aasdk::proto::data::MediaInfoChannel& ChannelDescriptor::media_infochannel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.media_infoChannel)
  return _internal_media_infochannel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_media_infochannel(
    ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.media_infochannel_);
  }
  _impl_.media_infochannel_ = reinterpret_cast<::aasdk::proto::data::MediaInfoChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.media_infoChannel)
}
inline ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_media_infochannel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000040u;
  ::aasdk::proto::data::MediaInfoChannel* released = _impl_.media_infochannel_;
  _impl_.media_infochannel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_media_infochannel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.media_infoChannel)

  _impl_._has_bits_[0] &= ~0x00000040u;
  ::aasdk::proto::data::MediaInfoChannel* temp = _impl_.media_infochannel_;
  _impl_.media_infochannel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_media_infochannel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.media_infochannel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::MediaInfoChannel>(GetArena());
    _impl_.media_infochannel_ = reinterpret_cast<::aasdk::proto::data::MediaInfoChannel*>(p);
  }
  return _impl_.media_infochannel_;
}
inline ::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_media_infochannel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000040u;
  ::aasdk::proto::data::MediaInfoChannel* _msg = _internal_mutable_media_infochannel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.media_infoChannel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_media_infochannel(::aasdk::proto::data::MediaInfoChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.media_infochannel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }

  _impl_.media_infochannel_ = reinterpret_cast<::aasdk::proto::data::MediaInfoChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.media_infoChannel)
}

// optional .aasdk.proto.data.VendorExtensionChannel vendor_extension_channel = 12;
inline bool ChannelDescriptor::has_vendor_extension_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.vendor_extension_channel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::VendorExtensionChannel& ChannelDescriptor::_internal_vendor_extension_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::VendorExtensionChannel* p = _impl_.vendor_extension_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::VendorExtensionChannel&>(::aasdk::proto::data::_VendorExtensionChannel_default_instance_);
}
inline const ::aasdk::proto::data::VendorExtensionChannel& ChannelDescriptor::vendor_extension_channel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
  return _internal_vendor_extension_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_vendor_extension_channel(
    ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vendor_extension_channel_);
  }
  _impl_.vendor_extension_channel_ = reinterpret_cast<::aasdk::proto::data::VendorExtensionChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
}
inline ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_vendor_extension_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000080u;
  ::aasdk::proto::data::VendorExtensionChannel* released = _impl_.vendor_extension_channel_;
  _impl_.vendor_extension_channel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_vendor_extension_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)

  _impl_._has_bits_[0] &= ~0x00000080u;
  ::aasdk::proto::data::VendorExtensionChannel* temp = _impl_.vendor_extension_channel_;
  _impl_.vendor_extension_channel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_vendor_extension_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vendor_extension_channel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::VendorExtensionChannel>(GetArena());
    _impl_.vendor_extension_channel_ = reinterpret_cast<::aasdk::proto::data::VendorExtensionChannel*>(p);
  }
  return _impl_.vendor_extension_channel_;
}
inline ::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_vendor_extension_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000080u;
  ::aasdk::proto::data::VendorExtensionChannel* _msg = _internal_mutable_vendor_extension_channel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_vendor_extension_channel(::aasdk::proto::data::VendorExtensionChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vendor_extension_channel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }

  _impl_.vendor_extension_channel_ = reinterpret_cast<::aasdk::proto::data::VendorExtensionChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
}

// optional .aasdk.proto.data.WifiChannel wifi_channel = 16;
inline bool ChannelDescriptor::has_wifi_channel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.wifi_channel_ != nullptr);
  return value;
}
inline const ::aasdk::proto::data::WifiChannel& ChannelDescriptor::_internal_wifi_channel() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::aasdk::proto::data::WifiChannel* p = _impl_.wifi_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::aasdk::proto::data::WifiChannel&>(::aasdk::proto::data::_WifiChannel_default_instance_);
}
inline const ::aasdk::proto::data::WifiChannel& ChannelDescriptor::wifi_channel() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.ChannelDescriptor.wifi_channel)
  return _internal_wifi_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_wifi_channel(
    ::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.wifi_channel_);
  }
  _impl_.wifi_channel_ = reinterpret_cast<::aasdk::proto::data::WifiChannel*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aasdk.proto.data.ChannelDescriptor.wifi_channel)
}
inline ::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE ChannelDescriptor::release_wifi_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000100u;
  ::aasdk::proto::data::WifiChannel* released = _impl_.wifi_channel_;
  _impl_.wifi_channel_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE ChannelDescriptor::unsafe_arena_release_wifi_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:aasdk.proto.data.ChannelDescriptor.wifi_channel)

  _impl_._has_bits_[0] &= ~0x00000100u;
  ::aasdk::proto::data::WifiChannel* temp = _impl_.wifi_channel_;
  _impl_.wifi_channel_ = nullptr;
  return temp;
}
inline ::aasdk::proto::data::WifiChannel* PROTOBUF_NONNULL ChannelDescriptor::_internal_mutable_wifi_channel() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.wifi_channel_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::aasdk::proto::data::WifiChannel>(GetArena());
    _impl_.wifi_channel_ = reinterpret_cast<::aasdk::proto::data::WifiChannel*>(p);
  }
  return _impl_.wifi_channel_;
}
inline ::aasdk::proto::data::WifiChannel* PROTOBUF_NONNULL ChannelDescriptor::mutable_wifi_channel()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000100u;
  ::aasdk::proto::data::WifiChannel* _msg = _internal_mutable_wifi_channel();
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.ChannelDescriptor.wifi_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_wifi_channel(::aasdk::proto::data::WifiChannel* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.wifi_channel_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }

  _impl_.wifi_channel_ = reinterpret_cast<::aasdk::proto::data::WifiChannel*>(value);
  // @@protoc_insertion_point(field_set_allocated:aasdk.proto.data.ChannelDescriptor.wifi_channel)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ChannelDescriptorData_2eproto_2epb_2eh
