// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HeadlightStatusEnum.proto
// Protobuf C++ Version: 6.31.0

#ifndef HeadlightStatusEnum_2eproto_2epb_2eh
#define HeadlightStatusEnum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_HeadlightStatusEnum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_HeadlightStatusEnum_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_HeadlightStatusEnum_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace enums {
enum HeadlightStatus_Enum : int;
extern const uint32_t HeadlightStatus_Enum_internal_data_[];
class HeadlightStatus;
struct HeadlightStatusDefaultTypeInternal;
extern HeadlightStatusDefaultTypeInternal _HeadlightStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull HeadlightStatus_class_data_;
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::aasdk::proto::enums::HeadlightStatus_Enum_internal_data_>
    internal::EnumTraitsImpl::value<::aasdk::proto::enums::HeadlightStatus_Enum>;
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace enums {
enum HeadlightStatus_Enum : int {
  HeadlightStatus_Enum_STATE_0 = 0,
  HeadlightStatus_Enum_STATE_1 = 1,
  HeadlightStatus_Enum_STATE_2 = 2,
  HeadlightStatus_Enum_STATE_3 = 3,
};

extern const uint32_t HeadlightStatus_Enum_internal_data_[];
inline constexpr HeadlightStatus_Enum HeadlightStatus_Enum_Enum_MIN =
    static_cast<HeadlightStatus_Enum>(0);
inline constexpr HeadlightStatus_Enum HeadlightStatus_Enum_Enum_MAX =
    static_cast<HeadlightStatus_Enum>(3);
inline bool HeadlightStatus_Enum_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int HeadlightStatus_Enum_Enum_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL HeadlightStatus_Enum_descriptor();
template <typename T>
const ::std::string& HeadlightStatus_Enum_Name(T value) {
  static_assert(::std::is_same<T, HeadlightStatus_Enum>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Enum_Name().");
  return HeadlightStatus_Enum_Name(static_cast<HeadlightStatus_Enum>(value));
}
template <>
inline const ::std::string& HeadlightStatus_Enum_Name(HeadlightStatus_Enum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<HeadlightStatus_Enum_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool HeadlightStatus_Enum_Parse(
    ::absl::string_view name, HeadlightStatus_Enum* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<HeadlightStatus_Enum>(HeadlightStatus_Enum_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class HeadlightStatus final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:aasdk.proto.enums.HeadlightStatus) */ {
 public:
  inline HeadlightStatus() : HeadlightStatus(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HeadlightStatus* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HeadlightStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HeadlightStatus(::google::protobuf::internal::ConstantInitialized);

  inline HeadlightStatus(const HeadlightStatus& from) : HeadlightStatus(nullptr, from) {}
  inline HeadlightStatus(HeadlightStatus&& from) noexcept
      : HeadlightStatus(nullptr, ::std::move(from)) {}
  inline HeadlightStatus& operator=(const HeadlightStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeadlightStatus& operator=(HeadlightStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeadlightStatus& default_instance() {
    return *reinterpret_cast<const HeadlightStatus*>(
        &_HeadlightStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(HeadlightStatus& a, HeadlightStatus& b) { a.Swap(&b); }
  inline void Swap(HeadlightStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeadlightStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeadlightStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<HeadlightStatus>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const HeadlightStatus& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const HeadlightStatus& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.enums.HeadlightStatus"; }

 protected:
  explicit HeadlightStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HeadlightStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HeadlightStatus& from);
  HeadlightStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HeadlightStatus&& from) noexcept
      : HeadlightStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Enum = HeadlightStatus_Enum;
  static constexpr Enum STATE_0 = HeadlightStatus_Enum_STATE_0;
  static constexpr Enum STATE_1 = HeadlightStatus_Enum_STATE_1;
  static constexpr Enum STATE_2 = HeadlightStatus_Enum_STATE_2;
  static constexpr Enum STATE_3 = HeadlightStatus_Enum_STATE_3;
  static inline bool Enum_IsValid(int value) {
    return HeadlightStatus_Enum_IsValid(value);
  }
  static constexpr Enum Enum_MIN = HeadlightStatus_Enum_Enum_MIN;
  static constexpr Enum Enum_MAX = HeadlightStatus_Enum_Enum_MAX;
  static constexpr int Enum_ARRAYSIZE = HeadlightStatus_Enum_Enum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Enum_descriptor() {
    return HeadlightStatus_Enum_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Enum_Name(T value) {
    return HeadlightStatus_Enum_Name(value);
  }
  static inline bool Enum_Parse(
      ::absl::string_view name, Enum* PROTOBUF_NONNULL value) {
    return HeadlightStatus_Enum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:aasdk.proto.enums.HeadlightStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HeadlightStatus& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_HeadlightStatusEnum_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HeadlightStatus_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HeadlightStatus

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace enums
}  // namespace proto
}  // namespace aasdk


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::aasdk::proto::enums::HeadlightStatus_Enum> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::aasdk::proto::enums::HeadlightStatus_Enum>() {
  return ::aasdk::proto::enums::HeadlightStatus_Enum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // HeadlightStatusEnum_2eproto_2epb_2eh
