// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NavigationImageOptionsData.proto
// Protobuf C++ Version: 6.31.0

#ifndef NavigationImageOptionsData_2eproto_2epb_2eh
#define NavigationImageOptionsData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_NavigationImageOptionsData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_NavigationImageOptionsData_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_NavigationImageOptionsData_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace data {
class NavigationImageOptions;
struct NavigationImageOptionsDefaultTypeInternal;
extern NavigationImageOptionsDefaultTypeInternal _NavigationImageOptions_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NavigationImageOptions_class_data_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace data {

// ===================================================================


// -------------------------------------------------------------------

class NavigationImageOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aasdk.proto.data.NavigationImageOptions) */ {
 public:
  inline NavigationImageOptions() : NavigationImageOptions(nullptr) {}
  ~NavigationImageOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NavigationImageOptions* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NavigationImageOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NavigationImageOptions(::google::protobuf::internal::ConstantInitialized);

  inline NavigationImageOptions(const NavigationImageOptions& from) : NavigationImageOptions(nullptr, from) {}
  inline NavigationImageOptions(NavigationImageOptions&& from) noexcept
      : NavigationImageOptions(nullptr, ::std::move(from)) {}
  inline NavigationImageOptions& operator=(const NavigationImageOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline NavigationImageOptions& operator=(NavigationImageOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NavigationImageOptions& default_instance() {
    return *reinterpret_cast<const NavigationImageOptions*>(
        &_NavigationImageOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NavigationImageOptions& a, NavigationImageOptions& b) { a.Swap(&b); }
  inline void Swap(NavigationImageOptions* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NavigationImageOptions* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NavigationImageOptions* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NavigationImageOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NavigationImageOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NavigationImageOptions& from) { NavigationImageOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NavigationImageOptions* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.data.NavigationImageOptions"; }

 protected:
  explicit NavigationImageOptions(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NavigationImageOptions(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NavigationImageOptions& from);
  NavigationImageOptions(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NavigationImageOptions&& from) noexcept
      : NavigationImageOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
    kColourDepthBitsFieldNumber = 3,
    kDunnoFieldNumber = 4,
  };
  // required int32 width = 1;
  bool has_width() const;
  void clear_width() ;
  ::int32_t width() const;
  void set_width(::int32_t value);

  private:
  ::int32_t _internal_width() const;
  void _internal_set_width(::int32_t value);

  public:
  // required int32 height = 2;
  bool has_height() const;
  void clear_height() ;
  ::int32_t height() const;
  void set_height(::int32_t value);

  private:
  ::int32_t _internal_height() const;
  void _internal_set_height(::int32_t value);

  public:
  // required int32 colour_depth_bits = 3;
  bool has_colour_depth_bits() const;
  void clear_colour_depth_bits() ;
  ::int32_t colour_depth_bits() const;
  void set_colour_depth_bits(::int32_t value);

  private:
  ::int32_t _internal_colour_depth_bits() const;
  void _internal_set_colour_depth_bits(::int32_t value);

  public:
  // required int32 dunno = 4;
  bool has_dunno() const;
  void clear_dunno() ;
  ::int32_t dunno() const;
  void set_dunno(::int32_t value);

  private:
  ::int32_t _internal_dunno() const;
  void _internal_set_dunno(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:aasdk.proto.data.NavigationImageOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NavigationImageOptions& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t width_;
    ::int32_t height_;
    ::int32_t colour_depth_bits_;
    ::int32_t dunno_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NavigationImageOptionsData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NavigationImageOptions_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NavigationImageOptions

// required int32 width = 1;
inline bool NavigationImageOptions::has_width() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void NavigationImageOptions::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t NavigationImageOptions::width() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.NavigationImageOptions.width)
  return _internal_width();
}
inline void NavigationImageOptions::set_width(::int32_t value) {
  _internal_set_width(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:aasdk.proto.data.NavigationImageOptions.width)
}
inline ::int32_t NavigationImageOptions::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void NavigationImageOptions::_internal_set_width(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// required int32 height = 2;
inline bool NavigationImageOptions::has_height() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void NavigationImageOptions::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t NavigationImageOptions::height() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.NavigationImageOptions.height)
  return _internal_height();
}
inline void NavigationImageOptions::set_height(::int32_t value) {
  _internal_set_height(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:aasdk.proto.data.NavigationImageOptions.height)
}
inline ::int32_t NavigationImageOptions::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void NavigationImageOptions::_internal_set_height(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// required int32 colour_depth_bits = 3;
inline bool NavigationImageOptions::has_colour_depth_bits() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void NavigationImageOptions::clear_colour_depth_bits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.colour_depth_bits_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t NavigationImageOptions::colour_depth_bits() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.NavigationImageOptions.colour_depth_bits)
  return _internal_colour_depth_bits();
}
inline void NavigationImageOptions::set_colour_depth_bits(::int32_t value) {
  _internal_set_colour_depth_bits(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:aasdk.proto.data.NavigationImageOptions.colour_depth_bits)
}
inline ::int32_t NavigationImageOptions::_internal_colour_depth_bits() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.colour_depth_bits_;
}
inline void NavigationImageOptions::_internal_set_colour_depth_bits(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.colour_depth_bits_ = value;
}

// required int32 dunno = 4;
inline bool NavigationImageOptions::has_dunno() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void NavigationImageOptions::clear_dunno() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dunno_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t NavigationImageOptions::dunno() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.NavigationImageOptions.dunno)
  return _internal_dunno();
}
inline void NavigationImageOptions::set_dunno(::int32_t value) {
  _internal_set_dunno(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:aasdk.proto.data.NavigationImageOptions.dunno)
}
inline ::int32_t NavigationImageOptions::_internal_dunno() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dunno_;
}
inline void NavigationImageOptions::_internal_set_dunno(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dunno_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // NavigationImageOptionsData_2eproto_2epb_2eh
