// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NightModeData.proto
// Protobuf C++ Version: 6.31.0

#include "NightModeData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace data {

inline constexpr NightMode::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        is_night_{false} {}

template <typename>
PROTOBUF_CONSTEXPR NightMode::NightMode(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NightMode_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NightModeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NightModeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NightModeDefaultTypeInternal() {}
  union {
    NightMode _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NightModeDefaultTypeInternal _NightMode_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_NightModeData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_NightModeData_2eproto = nullptr;
const ::uint32_t
    TableStruct_NightModeData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::NightMode, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::NightMode, _impl_.is_night_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::data::NightMode)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::data::_NightMode_default_instance_._instance,
};
const char descriptor_table_protodef_NightModeData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023NightModeData.proto\022\020aasdk.proto.data\""
    "\035\n\tNightMode\022\020\n\010is_night\030\001 \002(\010"
};
static ::absl::once_flag descriptor_table_NightModeData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_NightModeData_2eproto = {
    false,
    false,
    70,
    descriptor_table_protodef_NightModeData_2eproto,
    "NightModeData.proto",
    &descriptor_table_NightModeData_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_NightModeData_2eproto::offsets,
    file_level_enum_descriptors_NightModeData_2eproto,
    file_level_service_descriptors_NightModeData_2eproto,
};
namespace aasdk {
namespace proto {
namespace data {
// ===================================================================

class NightMode::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NightMode>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NightMode, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

NightMode::NightMode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NightMode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.data.NightMode)
}
NightMode::NightMode(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NightMode& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NightMode_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE NightMode::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void NightMode::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_night_ = {};
}
NightMode::~NightMode() {
  // @@protoc_insertion_point(destructor:aasdk.proto.data.NightMode)
  SharedDtor(*this);
}
inline void NightMode::SharedDtor(MessageLite& self) {
  NightMode& this_ = static_cast<NightMode&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NightMode::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NightMode(arena);
}
constexpr auto NightMode::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NightMode),
                                            alignof(NightMode));
}
constexpr auto NightMode::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NightMode_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          NightMode::IsInitializedImpl,
          &NightMode::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NightMode>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NightMode::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NightMode>(), &NightMode::ByteSizeLong,
              &NightMode::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NightMode, _impl_._cached_size_),
          false,
      },
      &NightMode::kDescriptorMethods,
      &descriptor_table_NightModeData_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NightMode_class_data_ =
        NightMode::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NightMode::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NightMode_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NightMode_class_data_.tc_table);
  return NightMode_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
NightMode::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NightMode, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NightMode_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::data::NightMode>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required bool is_night = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NightMode, _impl_.is_night_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(NightMode, _impl_.is_night_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required bool is_night = 1;
    {PROTOBUF_FIELD_OFFSET(NightMode, _impl_.is_night_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void NightMode::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.data.NightMode)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.is_night_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NightMode::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NightMode& this_ = static_cast<const NightMode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NightMode::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NightMode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.data.NightMode)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required bool is_night = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this_._internal_is_night(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.data.NightMode)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NightMode::ByteSizeLong(const MessageLite& base) {
  const NightMode& this_ = static_cast<const NightMode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NightMode::ByteSizeLong() const {
  const NightMode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aasdk.proto.data.NightMode)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000001u & cached_has_bits) * 2;
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NightMode::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NightMode*>(&to_msg);
  auto& from = static_cast<const NightMode&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.data.NightMode)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_impl_.is_night_ = from._impl_.is_night_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NightMode::CopyFrom(const NightMode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.data.NightMode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NightMode::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const NightMode&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void NightMode::InternalSwap(NightMode* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.is_night_, other->_impl_.is_night_);
}

::google::protobuf::Metadata NightMode::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_NightModeData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
