// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RelativeInputEventData.proto
// Protobuf C++ Version: 6.31.0

#include "RelativeInputEventData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace data {

inline constexpr RelativeInputEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        scan_code_{0u},
        delta_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RelativeInputEvent::RelativeInputEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RelativeInputEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RelativeInputEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RelativeInputEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RelativeInputEventDefaultTypeInternal() {}
  union {
    RelativeInputEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RelativeInputEventDefaultTypeInternal _RelativeInputEvent_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_RelativeInputEventData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_RelativeInputEventData_2eproto = nullptr;
const ::uint32_t
    TableStruct_RelativeInputEventData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::RelativeInputEvent, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::RelativeInputEvent, _impl_.scan_code_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::RelativeInputEvent, _impl_.delta_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::data::RelativeInputEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::data::_RelativeInputEvent_default_instance_._instance,
};
const char descriptor_table_protodef_RelativeInputEventData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034RelativeInputEventData.proto\022\020aasdk.pr"
    "oto.data\"6\n\022RelativeInputEvent\022\021\n\tscan_c"
    "ode\030\001 \002(\r\022\r\n\005delta\030\002 \002(\005"
};
static ::absl::once_flag descriptor_table_RelativeInputEventData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_RelativeInputEventData_2eproto = {
    false,
    false,
    104,
    descriptor_table_protodef_RelativeInputEventData_2eproto,
    "RelativeInputEventData.proto",
    &descriptor_table_RelativeInputEventData_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_RelativeInputEventData_2eproto::offsets,
    file_level_enum_descriptors_RelativeInputEventData_2eproto,
    file_level_service_descriptors_RelativeInputEventData_2eproto,
};
namespace aasdk {
namespace proto {
namespace data {
// ===================================================================

class RelativeInputEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RelativeInputEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

RelativeInputEvent::RelativeInputEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RelativeInputEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.data.RelativeInputEvent)
}
RelativeInputEvent::RelativeInputEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RelativeInputEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RelativeInputEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE RelativeInputEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void RelativeInputEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, scan_code_),
           0,
           offsetof(Impl_, delta_) -
               offsetof(Impl_, scan_code_) +
               sizeof(Impl_::delta_));
}
RelativeInputEvent::~RelativeInputEvent() {
  // @@protoc_insertion_point(destructor:aasdk.proto.data.RelativeInputEvent)
  SharedDtor(*this);
}
inline void RelativeInputEvent::SharedDtor(MessageLite& self) {
  RelativeInputEvent& this_ = static_cast<RelativeInputEvent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RelativeInputEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RelativeInputEvent(arena);
}
constexpr auto RelativeInputEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RelativeInputEvent),
                                            alignof(RelativeInputEvent));
}
constexpr auto RelativeInputEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RelativeInputEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          RelativeInputEvent::IsInitializedImpl,
          &RelativeInputEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RelativeInputEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RelativeInputEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RelativeInputEvent>(), &RelativeInputEvent::ByteSizeLong,
              &RelativeInputEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_._cached_size_),
          false,
      },
      &RelativeInputEvent::kDescriptorMethods,
      &descriptor_table_RelativeInputEventData_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RelativeInputEvent_class_data_ =
        RelativeInputEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RelativeInputEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RelativeInputEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RelativeInputEvent_class_data_.tc_table);
  return RelativeInputEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
RelativeInputEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RelativeInputEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::data::RelativeInputEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required int32 delta = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RelativeInputEvent, _impl_.delta_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_.delta_)}},
    // required uint32 scan_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RelativeInputEvent, _impl_.scan_code_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_.scan_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required uint32 scan_code = 1;
    {PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_.scan_code_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // required int32 delta = 2;
    {PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_.delta_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RelativeInputEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.data.RelativeInputEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.scan_code_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.delta_) -
        reinterpret_cast<char*>(&_impl_.scan_code_)) + sizeof(_impl_.delta_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RelativeInputEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RelativeInputEvent& this_ = static_cast<const RelativeInputEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RelativeInputEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RelativeInputEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.data.RelativeInputEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required uint32 scan_code = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_scan_code(), target);
  }

  // required int32 delta = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_delta(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.data.RelativeInputEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RelativeInputEvent::ByteSizeLong(const MessageLite& base) {
  const RelativeInputEvent& this_ = static_cast<const RelativeInputEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RelativeInputEvent::ByteSizeLong() const {
  const RelativeInputEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aasdk.proto.data.RelativeInputEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // required uint32 scan_code = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_scan_code());
    }
    // required int32 delta = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_delta());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RelativeInputEvent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RelativeInputEvent*>(&to_msg);
  auto& from = static_cast<const RelativeInputEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.data.RelativeInputEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.scan_code_ = from._impl_.scan_code_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.delta_ = from._impl_.delta_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RelativeInputEvent::CopyFrom(const RelativeInputEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.data.RelativeInputEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RelativeInputEvent::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const RelativeInputEvent&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void RelativeInputEvent::InternalSwap(RelativeInputEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_.delta_)
      + sizeof(RelativeInputEvent::_impl_.delta_)
      - PROTOBUF_FIELD_OFFSET(RelativeInputEvent, _impl_.scan_code_)>(
          reinterpret_cast<char*>(&_impl_.scan_code_),
          reinterpret_cast<char*>(&other->_impl_.scan_code_));
}

::google::protobuf::Metadata RelativeInputEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_RelativeInputEventData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
