// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SensorChannelData.proto
// Protobuf C++ Version: 6.31.0

#ifndef SensorChannelData_2eproto_2epb_2eh
#define SensorChannelData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "SensorData.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SensorChannelData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SensorChannelData_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_SensorChannelData_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace data {
class SensorChannel;
struct SensorChannelDefaultTypeInternal;
extern SensorChannelDefaultTypeInternal _SensorChannel_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SensorChannel_class_data_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace data {

// ===================================================================


// -------------------------------------------------------------------

class SensorChannel final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aasdk.proto.data.SensorChannel) */ {
 public:
  inline SensorChannel() : SensorChannel(nullptr) {}
  ~SensorChannel() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SensorChannel* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SensorChannel));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SensorChannel(::google::protobuf::internal::ConstantInitialized);

  inline SensorChannel(const SensorChannel& from) : SensorChannel(nullptr, from) {}
  inline SensorChannel(SensorChannel&& from) noexcept
      : SensorChannel(nullptr, ::std::move(from)) {}
  inline SensorChannel& operator=(const SensorChannel& from) {
    CopyFrom(from);
    return *this;
  }
  inline SensorChannel& operator=(SensorChannel&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SensorChannel& default_instance() {
    return *reinterpret_cast<const SensorChannel*>(
        &_SensorChannel_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SensorChannel& a, SensorChannel& b) { a.Swap(&b); }
  inline void Swap(SensorChannel* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SensorChannel* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SensorChannel* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SensorChannel>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SensorChannel& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SensorChannel& from) { SensorChannel::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SensorChannel* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.data.SensorChannel"; }

 protected:
  explicit SensorChannel(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SensorChannel(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SensorChannel& from);
  SensorChannel(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SensorChannel&& from) noexcept
      : SensorChannel(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSensorsFieldNumber = 1,
  };
  // repeated .aasdk.proto.data.Sensor sensors = 1;
  int sensors_size() const;
  private:
  int _internal_sensors_size() const;

  public:
  void clear_sensors() ;
  ::aasdk::proto::data::Sensor* PROTOBUF_NONNULL mutable_sensors(int index);
  ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::Sensor>* PROTOBUF_NONNULL mutable_sensors();

  private:
  const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::Sensor>& _internal_sensors() const;
  ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::Sensor>* PROTOBUF_NONNULL _internal_mutable_sensors();
  public:
  const ::aasdk::proto::data::Sensor& sensors(int index) const;
  ::aasdk::proto::data::Sensor* PROTOBUF_NONNULL add_sensors();
  const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::Sensor>& sensors() const;
  // @@protoc_insertion_point(class_scope:aasdk.proto.data.SensorChannel)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SensorChannel& from_msg);
    ::google::protobuf::RepeatedPtrField< ::aasdk::proto::data::Sensor > sensors_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SensorChannelData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SensorChannel_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SensorChannel

// repeated .aasdk.proto.data.Sensor sensors = 1;
inline int SensorChannel::_internal_sensors_size() const {
  return _internal_sensors().size();
}
inline int SensorChannel::sensors_size() const {
  return _internal_sensors_size();
}
inline ::aasdk::proto::data::Sensor* PROTOBUF_NONNULL SensorChannel::mutable_sensors(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.SensorChannel.sensors)
  return _internal_mutable_sensors()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::Sensor>* PROTOBUF_NONNULL SensorChannel::mutable_sensors()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.data.SensorChannel.sensors)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_sensors();
}
inline const ::aasdk::proto::data::Sensor& SensorChannel::sensors(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.SensorChannel.sensors)
  return _internal_sensors().Get(index);
}
inline ::aasdk::proto::data::Sensor* PROTOBUF_NONNULL SensorChannel::add_sensors()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::aasdk::proto::data::Sensor* _add = _internal_mutable_sensors()->Add();
  // @@protoc_insertion_point(field_add:aasdk.proto.data.SensorChannel.sensors)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::Sensor>& SensorChannel::sensors() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aasdk.proto.data.SensorChannel.sensors)
  return _internal_sensors();
}
inline const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::Sensor>&
SensorChannel::_internal_sensors() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sensors_;
}
inline ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::Sensor>* PROTOBUF_NONNULL
SensorChannel::_internal_mutable_sensors() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.sensors_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SensorChannelData_2eproto_2epb_2eh
