// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ServiceDiscoveryResponseMessage.proto
// Protobuf C++ Version: 6.31.0

#include "ServiceDiscoveryResponseMessage.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace messages {

inline constexpr ServiceDiscoveryResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        channels_{},
        head_unit_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        car_model_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        car_year_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        car_serial_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        headunit_manufacturer_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        headunit_model_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sw_build_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sw_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        left_hand_drive_vehicle_{false},
        can_play_native_media_during_vr_{false},
        hide_clock_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ServiceDiscoveryResponse::ServiceDiscoveryResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ServiceDiscoveryResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ServiceDiscoveryResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServiceDiscoveryResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServiceDiscoveryResponseDefaultTypeInternal() {}
  union {
    ServiceDiscoveryResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServiceDiscoveryResponseDefaultTypeInternal _ServiceDiscoveryResponse_default_instance_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_ServiceDiscoveryResponseMessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_ServiceDiscoveryResponseMessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_ServiceDiscoveryResponseMessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_._has_bits_),
        15, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.channels_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.head_unit_name_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.car_model_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.car_year_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.car_serial_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.left_hand_drive_vehicle_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.headunit_manufacturer_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.headunit_model_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.sw_build_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.sw_version_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.can_play_native_media_during_vr_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::ServiceDiscoveryResponse, _impl_.hide_clock_),
        ~0u,
        0,
        1,
        2,
        3,
        8,
        4,
        5,
        6,
        7,
        9,
        10,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::messages::ServiceDiscoveryResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::messages::_ServiceDiscoveryResponse_default_instance_._instance,
};
const char descriptor_table_protodef_ServiceDiscoveryResponseMessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n%ServiceDiscoveryResponseMessage.proto\022"
    "\024aasdk.proto.messages\032\033ChannelDescriptor"
    "Data.proto\"\335\002\n\030ServiceDiscoveryResponse\022"
    "5\n\010channels\030\001 \003(\0132#.aasdk.proto.data.Cha"
    "nnelDescriptor\022\026\n\016head_unit_name\030\002 \002(\t\022\021"
    "\n\tcar_model\030\003 \002(\t\022\020\n\010car_year\030\004 \002(\t\022\022\n\nc"
    "ar_serial\030\005 \002(\t\022\037\n\027left_hand_drive_vehic"
    "le\030\006 \002(\010\022\035\n\025headunit_manufacturer\030\007 \002(\t\022"
    "\026\n\016headunit_model\030\010 \002(\t\022\020\n\010sw_build\030\t \002("
    "\t\022\022\n\nsw_version\030\n \002(\t\022\'\n\037can_play_native"
    "_media_during_vr\030\013 \002(\010\022\022\n\nhide_clock\030\014 \001"
    "(\010"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_ServiceDiscoveryResponseMessage_2eproto_deps[1] = {
        &::descriptor_table_ChannelDescriptorData_2eproto,
};
static ::absl::once_flag descriptor_table_ServiceDiscoveryResponseMessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ServiceDiscoveryResponseMessage_2eproto = {
    false,
    false,
    442,
    descriptor_table_protodef_ServiceDiscoveryResponseMessage_2eproto,
    "ServiceDiscoveryResponseMessage.proto",
    &descriptor_table_ServiceDiscoveryResponseMessage_2eproto_once,
    descriptor_table_ServiceDiscoveryResponseMessage_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_ServiceDiscoveryResponseMessage_2eproto::offsets,
    file_level_enum_descriptors_ServiceDiscoveryResponseMessage_2eproto,
    file_level_service_descriptors_ServiceDiscoveryResponseMessage_2eproto,
};
namespace aasdk {
namespace proto {
namespace messages {
// ===================================================================

class ServiceDiscoveryResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ServiceDiscoveryResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x000003ff) ^ 0x000003ff) != 0;
  }
};

void ServiceDiscoveryResponse::clear_channels() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.channels_.Clear();
}
ServiceDiscoveryResponse::ServiceDiscoveryResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ServiceDiscoveryResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.messages.ServiceDiscoveryResponse)
}
PROTOBUF_NDEBUG_INLINE ServiceDiscoveryResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::aasdk::proto::messages::ServiceDiscoveryResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        channels_{visibility, arena, from.channels_},
        head_unit_name_(arena, from.head_unit_name_),
        car_model_(arena, from.car_model_),
        car_year_(arena, from.car_year_),
        car_serial_(arena, from.car_serial_),
        headunit_manufacturer_(arena, from.headunit_manufacturer_),
        headunit_model_(arena, from.headunit_model_),
        sw_build_(arena, from.sw_build_),
        sw_version_(arena, from.sw_version_) {}

ServiceDiscoveryResponse::ServiceDiscoveryResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ServiceDiscoveryResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ServiceDiscoveryResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ServiceDiscoveryResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, left_hand_drive_vehicle_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, left_hand_drive_vehicle_),
           offsetof(Impl_, hide_clock_) -
               offsetof(Impl_, left_hand_drive_vehicle_) +
               sizeof(Impl_::hide_clock_));

  // @@protoc_insertion_point(copy_constructor:aasdk.proto.messages.ServiceDiscoveryResponse)
}
PROTOBUF_NDEBUG_INLINE ServiceDiscoveryResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        channels_{visibility, arena},
        head_unit_name_(arena),
        car_model_(arena),
        car_year_(arena),
        car_serial_(arena),
        headunit_manufacturer_(arena),
        headunit_model_(arena),
        sw_build_(arena),
        sw_version_(arena) {}

inline void ServiceDiscoveryResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, left_hand_drive_vehicle_),
           0,
           offsetof(Impl_, hide_clock_) -
               offsetof(Impl_, left_hand_drive_vehicle_) +
               sizeof(Impl_::hide_clock_));
}
ServiceDiscoveryResponse::~ServiceDiscoveryResponse() {
  // @@protoc_insertion_point(destructor:aasdk.proto.messages.ServiceDiscoveryResponse)
  SharedDtor(*this);
}
inline void ServiceDiscoveryResponse::SharedDtor(MessageLite& self) {
  ServiceDiscoveryResponse& this_ = static_cast<ServiceDiscoveryResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.head_unit_name_.Destroy();
  this_._impl_.car_model_.Destroy();
  this_._impl_.car_year_.Destroy();
  this_._impl_.car_serial_.Destroy();
  this_._impl_.headunit_manufacturer_.Destroy();
  this_._impl_.headunit_model_.Destroy();
  this_._impl_.sw_build_.Destroy();
  this_._impl_.sw_version_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ServiceDiscoveryResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ServiceDiscoveryResponse(arena);
}
constexpr auto ServiceDiscoveryResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.channels_) +
          decltype(ServiceDiscoveryResponse::_impl_.channels_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ServiceDiscoveryResponse), alignof(ServiceDiscoveryResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ServiceDiscoveryResponse::PlacementNew_,
                                 sizeof(ServiceDiscoveryResponse),
                                 alignof(ServiceDiscoveryResponse));
  }
}
constexpr auto ServiceDiscoveryResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ServiceDiscoveryResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          ServiceDiscoveryResponse::IsInitializedImpl,
          &ServiceDiscoveryResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ServiceDiscoveryResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ServiceDiscoveryResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ServiceDiscoveryResponse>(), &ServiceDiscoveryResponse::ByteSizeLong,
              &ServiceDiscoveryResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_._cached_size_),
          false,
      },
      &ServiceDiscoveryResponse::kDescriptorMethods,
      &descriptor_table_ServiceDiscoveryResponseMessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ServiceDiscoveryResponse_class_data_ =
        ServiceDiscoveryResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ServiceDiscoveryResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ServiceDiscoveryResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ServiceDiscoveryResponse_class_data_.tc_table);
  return ServiceDiscoveryResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 12, 1, 156, 2>
ServiceDiscoveryResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_._has_bits_),
    0, // no _extensions_
    12, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294963200,  // skipmap
    offsetof(decltype(_table_), field_entries),
    12,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ServiceDiscoveryResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::messages::ServiceDiscoveryResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .aasdk.proto.data.ChannelDescriptor channels = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.channels_)}},
    // required string head_unit_name = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.head_unit_name_)}},
    // required string car_model = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.car_model_)}},
    // required string car_year = 4;
    {::_pbi::TcParser::FastSS1,
     {34, 2, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.car_year_)}},
    // required string car_serial = 5;
    {::_pbi::TcParser::FastSS1,
     {42, 3, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.car_serial_)}},
    // required bool left_hand_drive_vehicle = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ServiceDiscoveryResponse, _impl_.left_hand_drive_vehicle_), 8>(),
     {48, 8, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.left_hand_drive_vehicle_)}},
    // required string headunit_manufacturer = 7;
    {::_pbi::TcParser::FastSS1,
     {58, 4, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.headunit_manufacturer_)}},
    // required string headunit_model = 8;
    {::_pbi::TcParser::FastSS1,
     {66, 5, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.headunit_model_)}},
    // required string sw_build = 9;
    {::_pbi::TcParser::FastSS1,
     {74, 6, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.sw_build_)}},
    // required string sw_version = 10;
    {::_pbi::TcParser::FastSS1,
     {82, 7, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.sw_version_)}},
    // required bool can_play_native_media_during_vr = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ServiceDiscoveryResponse, _impl_.can_play_native_media_during_vr_), 9>(),
     {88, 9, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.can_play_native_media_during_vr_)}},
    // optional bool hide_clock = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ServiceDiscoveryResponse, _impl_.hide_clock_), 10>(),
     {96, 10, 0, PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.hide_clock_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .aasdk.proto.data.ChannelDescriptor channels = 1;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.channels_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // required string head_unit_name = 2;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.head_unit_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string car_model = 3;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.car_model_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string car_year = 4;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.car_year_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string car_serial = 5;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.car_serial_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required bool left_hand_drive_vehicle = 6;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.left_hand_drive_vehicle_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // required string headunit_manufacturer = 7;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.headunit_manufacturer_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string headunit_model = 8;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.headunit_model_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string sw_build = 9;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.sw_build_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string sw_version = 10;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.sw_version_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required bool can_play_native_media_during_vr = 11;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.can_play_native_media_during_vr_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool hide_clock = 12;
    {PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.hide_clock_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aasdk::proto::data::ChannelDescriptor>()},
  }},
  {{
    "\55\0\16\11\10\12\0\25\16\10\12\0\0\0\0\0"
    "aasdk.proto.messages.ServiceDiscoveryResponse"
    "head_unit_name"
    "car_model"
    "car_year"
    "car_serial"
    "headunit_manufacturer"
    "headunit_model"
    "sw_build"
    "sw_version"
  }},
};
PROTOBUF_NOINLINE void ServiceDiscoveryResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.messages.ServiceDiscoveryResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.channels_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.head_unit_name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.car_model_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.car_year_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _impl_.car_serial_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _impl_.headunit_manufacturer_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      _impl_.headunit_model_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      _impl_.sw_build_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000080u) != 0) {
      _impl_.sw_version_.ClearNonDefaultToEmpty();
    }
  }
  ::memset(&_impl_.left_hand_drive_vehicle_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.hide_clock_) -
      reinterpret_cast<char*>(&_impl_.left_hand_drive_vehicle_)) + sizeof(_impl_.hide_clock_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ServiceDiscoveryResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ServiceDiscoveryResponse& this_ = static_cast<const ServiceDiscoveryResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ServiceDiscoveryResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ServiceDiscoveryResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.messages.ServiceDiscoveryResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .aasdk.proto.data.ChannelDescriptor channels = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_channels_size());
       i < n; i++) {
    const auto& repfield = this_._internal_channels().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // required string head_unit_name = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_head_unit_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.ServiceDiscoveryResponse.head_unit_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // required string car_model = 3;
  if ((cached_has_bits & 0x00000002u) != 0) {
    const ::std::string& _s = this_._internal_car_model();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.ServiceDiscoveryResponse.car_model");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // required string car_year = 4;
  if ((cached_has_bits & 0x00000004u) != 0) {
    const ::std::string& _s = this_._internal_car_year();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.ServiceDiscoveryResponse.car_year");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // required string car_serial = 5;
  if ((cached_has_bits & 0x00000008u) != 0) {
    const ::std::string& _s = this_._internal_car_serial();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.ServiceDiscoveryResponse.car_serial");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // required bool left_hand_drive_vehicle = 6;
  if ((cached_has_bits & 0x00000100u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        6, this_._internal_left_hand_drive_vehicle(), target);
  }

  // required string headunit_manufacturer = 7;
  if ((cached_has_bits & 0x00000010u) != 0) {
    const ::std::string& _s = this_._internal_headunit_manufacturer();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.ServiceDiscoveryResponse.headunit_manufacturer");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // required string headunit_model = 8;
  if ((cached_has_bits & 0x00000020u) != 0) {
    const ::std::string& _s = this_._internal_headunit_model();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.ServiceDiscoveryResponse.headunit_model");
    target = stream->WriteStringMaybeAliased(8, _s, target);
  }

  // required string sw_build = 9;
  if ((cached_has_bits & 0x00000040u) != 0) {
    const ::std::string& _s = this_._internal_sw_build();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.ServiceDiscoveryResponse.sw_build");
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  // required string sw_version = 10;
  if ((cached_has_bits & 0x00000080u) != 0) {
    const ::std::string& _s = this_._internal_sw_version();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.ServiceDiscoveryResponse.sw_version");
    target = stream->WriteStringMaybeAliased(10, _s, target);
  }

  // required bool can_play_native_media_during_vr = 11;
  if ((cached_has_bits & 0x00000200u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        11, this_._internal_can_play_native_media_during_vr(), target);
  }

  // optional bool hide_clock = 12;
  if ((cached_has_bits & 0x00000400u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        12, this_._internal_hide_clock(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.messages.ServiceDiscoveryResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ServiceDiscoveryResponse::ByteSizeLong(const MessageLite& base) {
  const ServiceDiscoveryResponse& this_ = static_cast<const ServiceDiscoveryResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ServiceDiscoveryResponse::ByteSizeLong() const {
  const ServiceDiscoveryResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aasdk.proto.messages.ServiceDiscoveryResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .aasdk.proto.data.ChannelDescriptor channels = 1;
    {
      total_size += 1UL * this_._internal_channels_size();
      for (const auto& msg : this_._internal_channels()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x00000700u & cached_has_bits) * 2;
  if ((cached_has_bits & 0x000000ffu) != 0) {
    // required string head_unit_name = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_head_unit_name());
    }
    // required string car_model = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_car_model());
    }
    // required string car_year = 4;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_car_year());
    }
    // required string car_serial = 5;
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_car_serial());
    }
    // required string headunit_manufacturer = 7;
    if ((cached_has_bits & 0x00000010u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_headunit_manufacturer());
    }
    // required string headunit_model = 8;
    if ((cached_has_bits & 0x00000020u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_headunit_model());
    }
    // required string sw_build = 9;
    if ((cached_has_bits & 0x00000040u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_sw_build());
    }
    // required string sw_version = 10;
    if ((cached_has_bits & 0x00000080u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_sw_version());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ServiceDiscoveryResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ServiceDiscoveryResponse*>(&to_msg);
  auto& from = static_cast<const ServiceDiscoveryResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.messages.ServiceDiscoveryResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_channels()->MergeFrom(
      from._internal_channels());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_head_unit_name(from._internal_head_unit_name());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_internal_set_car_model(from._internal_car_model());
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_internal_set_car_year(from._internal_car_year());
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _this->_internal_set_car_serial(from._internal_car_serial());
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _this->_internal_set_headunit_manufacturer(from._internal_headunit_manufacturer());
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      _this->_internal_set_headunit_model(from._internal_headunit_model());
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      _this->_internal_set_sw_build(from._internal_sw_build());
    }
    if ((cached_has_bits & 0x00000080u) != 0) {
      _this->_internal_set_sw_version(from._internal_sw_version());
    }
  }
  if ((cached_has_bits & 0x00000700u) != 0) {
    if ((cached_has_bits & 0x00000100u) != 0) {
      _this->_impl_.left_hand_drive_vehicle_ = from._impl_.left_hand_drive_vehicle_;
    }
    if ((cached_has_bits & 0x00000200u) != 0) {
      _this->_impl_.can_play_native_media_during_vr_ = from._impl_.can_play_native_media_during_vr_;
    }
    if ((cached_has_bits & 0x00000400u) != 0) {
      _this->_impl_.hide_clock_ = from._impl_.hide_clock_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServiceDiscoveryResponse::CopyFrom(const ServiceDiscoveryResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.messages.ServiceDiscoveryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ServiceDiscoveryResponse::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const ServiceDiscoveryResponse&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_channels()))
    return false;
  return true;
}

void ServiceDiscoveryResponse::InternalSwap(ServiceDiscoveryResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.channels_.InternalSwap(&other->_impl_.channels_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.head_unit_name_, &other->_impl_.head_unit_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.car_model_, &other->_impl_.car_model_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.car_year_, &other->_impl_.car_year_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.car_serial_, &other->_impl_.car_serial_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.headunit_manufacturer_, &other->_impl_.headunit_manufacturer_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.headunit_model_, &other->_impl_.headunit_model_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sw_build_, &other->_impl_.sw_build_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sw_version_, &other->_impl_.sw_version_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.hide_clock_)
      + sizeof(ServiceDiscoveryResponse::_impl_.hide_clock_)
      - PROTOBUF_FIELD_OFFSET(ServiceDiscoveryResponse, _impl_.left_hand_drive_vehicle_)>(
          reinterpret_cast<char*>(&_impl_.left_hand_drive_vehicle_),
          reinterpret_cast<char*>(&other->_impl_.left_hand_drive_vehicle_));
}

::google::protobuf::Metadata ServiceDiscoveryResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_ServiceDiscoveryResponseMessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
