// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VersionResponseStatusEnum.proto
// Protobuf C++ Version: 6.31.0

#ifndef VersionResponseStatusEnum_2eproto_2epb_2eh
#define VersionResponseStatusEnum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_VersionResponseStatusEnum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_VersionResponseStatusEnum_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_VersionResponseStatusEnum_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace enums {
enum VersionResponseStatus_Enum : int;
extern const uint32_t VersionResponseStatus_Enum_internal_data_[];
class VersionResponseStatus;
struct VersionResponseStatusDefaultTypeInternal;
extern VersionResponseStatusDefaultTypeInternal _VersionResponseStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull VersionResponseStatus_class_data_;
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::aasdk::proto::enums::VersionResponseStatus_Enum_internal_data_>
    internal::EnumTraitsImpl::value<::aasdk::proto::enums::VersionResponseStatus_Enum>;
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace enums {
enum VersionResponseStatus_Enum : int {
  VersionResponseStatus_Enum_MATCH = 0,
  VersionResponseStatus_Enum_MISMATCH = 65535,
};

extern const uint32_t VersionResponseStatus_Enum_internal_data_[];
inline constexpr VersionResponseStatus_Enum VersionResponseStatus_Enum_Enum_MIN =
    static_cast<VersionResponseStatus_Enum>(0);
inline constexpr VersionResponseStatus_Enum VersionResponseStatus_Enum_Enum_MAX =
    static_cast<VersionResponseStatus_Enum>(65535);
inline bool VersionResponseStatus_Enum_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, VersionResponseStatus_Enum_internal_data_);
}
inline constexpr int VersionResponseStatus_Enum_Enum_ARRAYSIZE = 65535 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL VersionResponseStatus_Enum_descriptor();
template <typename T>
const ::std::string& VersionResponseStatus_Enum_Name(T value) {
  static_assert(::std::is_same<T, VersionResponseStatus_Enum>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Enum_Name().");
  return ::google::protobuf::internal::NameOfEnum(VersionResponseStatus_Enum_descriptor(), value);
}
inline bool VersionResponseStatus_Enum_Parse(
    ::absl::string_view name, VersionResponseStatus_Enum* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<VersionResponseStatus_Enum>(VersionResponseStatus_Enum_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class VersionResponseStatus final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:aasdk.proto.enums.VersionResponseStatus) */ {
 public:
  inline VersionResponseStatus() : VersionResponseStatus(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VersionResponseStatus* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VersionResponseStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VersionResponseStatus(::google::protobuf::internal::ConstantInitialized);

  inline VersionResponseStatus(const VersionResponseStatus& from) : VersionResponseStatus(nullptr, from) {}
  inline VersionResponseStatus(VersionResponseStatus&& from) noexcept
      : VersionResponseStatus(nullptr, ::std::move(from)) {}
  inline VersionResponseStatus& operator=(const VersionResponseStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline VersionResponseStatus& operator=(VersionResponseStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VersionResponseStatus& default_instance() {
    return *reinterpret_cast<const VersionResponseStatus*>(
        &_VersionResponseStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VersionResponseStatus& a, VersionResponseStatus& b) { a.Swap(&b); }
  inline void Swap(VersionResponseStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VersionResponseStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VersionResponseStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<VersionResponseStatus>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const VersionResponseStatus& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const VersionResponseStatus& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.enums.VersionResponseStatus"; }

 protected:
  explicit VersionResponseStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VersionResponseStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VersionResponseStatus& from);
  VersionResponseStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VersionResponseStatus&& from) noexcept
      : VersionResponseStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Enum = VersionResponseStatus_Enum;
  static constexpr Enum MATCH = VersionResponseStatus_Enum_MATCH;
  static constexpr Enum MISMATCH = VersionResponseStatus_Enum_MISMATCH;
  static inline bool Enum_IsValid(int value) {
    return VersionResponseStatus_Enum_IsValid(value);
  }
  static constexpr Enum Enum_MIN = VersionResponseStatus_Enum_Enum_MIN;
  static constexpr Enum Enum_MAX = VersionResponseStatus_Enum_Enum_MAX;
  static constexpr int Enum_ARRAYSIZE = VersionResponseStatus_Enum_Enum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Enum_descriptor() {
    return VersionResponseStatus_Enum_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Enum_Name(T value) {
    return VersionResponseStatus_Enum_Name(value);
  }
  static inline bool Enum_Parse(
      ::absl::string_view name, Enum* PROTOBUF_NONNULL value) {
    return VersionResponseStatus_Enum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:aasdk.proto.enums.VersionResponseStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const VersionResponseStatus& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_VersionResponseStatusEnum_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull VersionResponseStatus_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VersionResponseStatus

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace enums
}  // namespace proto
}  // namespace aasdk


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::aasdk::proto::enums::VersionResponseStatus_Enum> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::aasdk::proto::enums::VersionResponseStatus_Enum>() {
  return ::aasdk::proto::enums::VersionResponseStatus_Enum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // VersionResponseStatusEnum_2eproto_2epb_2eh
