// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: VideoFocusModeEnum.proto
// Protobuf C++ Version: 6.31.0

#include "VideoFocusModeEnum.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace enums {
template <typename>
PROTOBUF_CONSTEXPR VideoFocusMode::VideoFocusMode(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(VideoFocusMode_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct VideoFocusModeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VideoFocusModeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VideoFocusModeDefaultTypeInternal() {}
  union {
    VideoFocusMode _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VideoFocusModeDefaultTypeInternal _VideoFocusMode_default_instance_;
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_VideoFocusModeEnum_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_VideoFocusModeEnum_2eproto = nullptr;
const ::uint32_t
    TableStruct_VideoFocusModeEnum_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::enums::VideoFocusMode)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::enums::_VideoFocusMode_default_instance_._instance,
};
const char descriptor_table_protodef_VideoFocusModeEnum_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030VideoFocusModeEnum.proto\022\021aasdk.proto."
    "enums\">\n\016VideoFocusMode\",\n\004Enum\022\010\n\004NONE\020"
    "\000\022\013\n\007FOCUSED\020\001\022\r\n\tUNFOCUSED\020\002"
};
static ::absl::once_flag descriptor_table_VideoFocusModeEnum_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_VideoFocusModeEnum_2eproto = {
    false,
    false,
    109,
    descriptor_table_protodef_VideoFocusModeEnum_2eproto,
    "VideoFocusModeEnum.proto",
    &descriptor_table_VideoFocusModeEnum_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_VideoFocusModeEnum_2eproto::offsets,
    file_level_enum_descriptors_VideoFocusModeEnum_2eproto,
    file_level_service_descriptors_VideoFocusModeEnum_2eproto,
};
namespace aasdk {
namespace proto {
namespace enums {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL VideoFocusMode_Enum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_VideoFocusModeEnum_2eproto);
  return file_level_enum_descriptors_VideoFocusModeEnum_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t VideoFocusMode_Enum_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class VideoFocusMode::_Internal {
 public:
};

VideoFocusMode::VideoFocusMode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, VideoFocusMode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.enums.VideoFocusMode)
}
VideoFocusMode::VideoFocusMode(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VideoFocusMode& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, VideoFocusMode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VideoFocusMode* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:aasdk.proto.enums.VideoFocusMode)
}

inline void* PROTOBUF_NONNULL VideoFocusMode::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VideoFocusMode(arena);
}
constexpr auto VideoFocusMode::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(VideoFocusMode),
                                            alignof(VideoFocusMode));
}
constexpr auto VideoFocusMode::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_VideoFocusMode_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &VideoFocusMode::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<VideoFocusMode>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VideoFocusMode::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<VideoFocusMode>(), &VideoFocusMode::ByteSizeLong,
              &VideoFocusMode::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VideoFocusMode, _impl_._cached_size_),
          false,
      },
      &VideoFocusMode::kDescriptorMethods,
      &descriptor_table_VideoFocusModeEnum_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VideoFocusMode_class_data_ =
        VideoFocusMode::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VideoFocusMode::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VideoFocusMode_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VideoFocusMode_class_data_.tc_table);
  return VideoFocusMode_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
VideoFocusMode::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    VideoFocusMode_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::enums::VideoFocusMode>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata VideoFocusMode::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_VideoFocusModeEnum_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
