// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AVChannelData.proto
// Protobuf C++ Version: 6.31.0

#ifndef AVChannelData_2eproto_2epb_2eh
#define AVChannelData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "AVStreamTypeEnum.pb.h"
#include "AudioTypeEnum.pb.h"
#include "AudioConfigData.pb.h"
#include "VideoConfigData.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AVChannelData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_AVChannelData_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_AVChannelData_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace data {
class AVChannel;
struct AVChannelDefaultTypeInternal;
extern AVChannelDefaultTypeInternal _AVChannel_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AVChannel_class_data_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace data {

// ===================================================================


// -------------------------------------------------------------------

class AVChannel final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aasdk.proto.data.AVChannel) */ {
 public:
  inline AVChannel() : AVChannel(nullptr) {}
  ~AVChannel() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AVChannel* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AVChannel));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AVChannel(::google::protobuf::internal::ConstantInitialized);

  inline AVChannel(const AVChannel& from) : AVChannel(nullptr, from) {}
  inline AVChannel(AVChannel&& from) noexcept
      : AVChannel(nullptr, ::std::move(from)) {}
  inline AVChannel& operator=(const AVChannel& from) {
    CopyFrom(from);
    return *this;
  }
  inline AVChannel& operator=(AVChannel&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AVChannel& default_instance() {
    return *reinterpret_cast<const AVChannel*>(
        &_AVChannel_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AVChannel& a, AVChannel& b) { a.Swap(&b); }
  inline void Swap(AVChannel* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AVChannel* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AVChannel* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AVChannel>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AVChannel& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AVChannel& from) { AVChannel::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AVChannel* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.data.AVChannel"; }

 protected:
  explicit AVChannel(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AVChannel(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AVChannel& from);
  AVChannel(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AVChannel&& from) noexcept
      : AVChannel(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAudioConfigsFieldNumber = 3,
    kVideoConfigsFieldNumber = 4,
    kStreamTypeFieldNumber = 1,
    kAudioTypeFieldNumber = 2,
    kAvailableWhileInCallFieldNumber = 5,
  };
  // repeated .aasdk.proto.data.AudioConfig audio_configs = 3;
  int audio_configs_size() const;
  private:
  int _internal_audio_configs_size() const;

  public:
  void clear_audio_configs() ;
  ::aasdk::proto::data::AudioConfig* PROTOBUF_NONNULL mutable_audio_configs(int index);
  ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::AudioConfig>* PROTOBUF_NONNULL mutable_audio_configs();

  private:
  const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::AudioConfig>& _internal_audio_configs() const;
  ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::AudioConfig>* PROTOBUF_NONNULL _internal_mutable_audio_configs();
  public:
  const ::aasdk::proto::data::AudioConfig& audio_configs(int index) const;
  ::aasdk::proto::data::AudioConfig* PROTOBUF_NONNULL add_audio_configs();
  const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::AudioConfig>& audio_configs() const;
  // repeated .aasdk.proto.data.VideoConfig video_configs = 4;
  int video_configs_size() const;
  private:
  int _internal_video_configs_size() const;

  public:
  void clear_video_configs() ;
  ::aasdk::proto::data::VideoConfig* PROTOBUF_NONNULL mutable_video_configs(int index);
  ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::VideoConfig>* PROTOBUF_NONNULL mutable_video_configs();

  private:
  const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::VideoConfig>& _internal_video_configs() const;
  ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::VideoConfig>* PROTOBUF_NONNULL _internal_mutable_video_configs();
  public:
  const ::aasdk::proto::data::VideoConfig& video_configs(int index) const;
  ::aasdk::proto::data::VideoConfig* PROTOBUF_NONNULL add_video_configs();
  const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::VideoConfig>& video_configs() const;
  // required .aasdk.proto.enums.AVStreamType.Enum stream_type = 1;
  bool has_stream_type() const;
  void clear_stream_type() ;
  ::aasdk::proto::enums::AVStreamType_Enum stream_type() const;
  void set_stream_type(::aasdk::proto::enums::AVStreamType_Enum value);

  private:
  ::aasdk::proto::enums::AVStreamType_Enum _internal_stream_type() const;
  void _internal_set_stream_type(::aasdk::proto::enums::AVStreamType_Enum value);

  public:
  // optional .aasdk.proto.enums.AudioType.Enum audio_type = 2;
  bool has_audio_type() const;
  void clear_audio_type() ;
  ::aasdk::proto::enums::AudioType_Enum audio_type() const;
  void set_audio_type(::aasdk::proto::enums::AudioType_Enum value);

  private:
  ::aasdk::proto::enums::AudioType_Enum _internal_audio_type() const;
  void _internal_set_audio_type(::aasdk::proto::enums::AudioType_Enum value);

  public:
  // optional bool available_while_in_call = 5;
  bool has_available_while_in_call() const;
  void clear_available_while_in_call() ;
  bool available_while_in_call() const;
  void set_available_while_in_call(bool value);

  private:
  bool _internal_available_while_in_call() const;
  void _internal_set_available_while_in_call(bool value);

  public:
  // @@protoc_insertion_point(class_scope:aasdk.proto.data.AVChannel)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AVChannel& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::aasdk::proto::data::AudioConfig > audio_configs_;
    ::google::protobuf::RepeatedPtrField< ::aasdk::proto::data::VideoConfig > video_configs_;
    int stream_type_;
    int audio_type_;
    bool available_while_in_call_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AVChannelData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AVChannel_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AVChannel

// required .aasdk.proto.enums.AVStreamType.Enum stream_type = 1;
inline bool AVChannel::has_stream_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void AVChannel::clear_stream_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stream_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::aasdk::proto::enums::AVStreamType_Enum AVChannel::stream_type() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.AVChannel.stream_type)
  return _internal_stream_type();
}
inline void AVChannel::set_stream_type(::aasdk::proto::enums::AVStreamType_Enum value) {
  _internal_set_stream_type(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:aasdk.proto.data.AVChannel.stream_type)
}
inline ::aasdk::proto::enums::AVStreamType_Enum AVChannel::_internal_stream_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::aasdk::proto::enums::AVStreamType_Enum>(_impl_.stream_type_);
}
inline void AVChannel::_internal_set_stream_type(::aasdk::proto::enums::AVStreamType_Enum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::aasdk::proto::enums::AVStreamType_Enum_internal_data_));
                                          _impl_.stream_type_ = value;
}

// optional .aasdk.proto.enums.AudioType.Enum audio_type = 2;
inline bool AVChannel::has_audio_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void AVChannel::clear_audio_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.audio_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::aasdk::proto::enums::AudioType_Enum AVChannel::audio_type() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.AVChannel.audio_type)
  return _internal_audio_type();
}
inline void AVChannel::set_audio_type(::aasdk::proto::enums::AudioType_Enum value) {
  _internal_set_audio_type(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:aasdk.proto.data.AVChannel.audio_type)
}
inline ::aasdk::proto::enums::AudioType_Enum AVChannel::_internal_audio_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::aasdk::proto::enums::AudioType_Enum>(_impl_.audio_type_);
}
inline void AVChannel::_internal_set_audio_type(::aasdk::proto::enums::AudioType_Enum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::aasdk::proto::enums::AudioType_Enum_internal_data_));
                                          _impl_.audio_type_ = value;
}

// repeated .aasdk.proto.data.AudioConfig audio_configs = 3;
inline int AVChannel::_internal_audio_configs_size() const {
  return _internal_audio_configs().size();
}
inline int AVChannel::audio_configs_size() const {
  return _internal_audio_configs_size();
}
inline ::aasdk::proto::data::AudioConfig* PROTOBUF_NONNULL AVChannel::mutable_audio_configs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.AVChannel.audio_configs)
  return _internal_mutable_audio_configs()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::AudioConfig>* PROTOBUF_NONNULL AVChannel::mutable_audio_configs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.data.AVChannel.audio_configs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_audio_configs();
}
inline const ::aasdk::proto::data::AudioConfig& AVChannel::audio_configs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.AVChannel.audio_configs)
  return _internal_audio_configs().Get(index);
}
inline ::aasdk::proto::data::AudioConfig* PROTOBUF_NONNULL AVChannel::add_audio_configs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::aasdk::proto::data::AudioConfig* _add = _internal_mutable_audio_configs()->Add();
  // @@protoc_insertion_point(field_add:aasdk.proto.data.AVChannel.audio_configs)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::AudioConfig>& AVChannel::audio_configs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aasdk.proto.data.AVChannel.audio_configs)
  return _internal_audio_configs();
}
inline const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::AudioConfig>&
AVChannel::_internal_audio_configs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.audio_configs_;
}
inline ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::AudioConfig>* PROTOBUF_NONNULL
AVChannel::_internal_mutable_audio_configs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.audio_configs_;
}

// repeated .aasdk.proto.data.VideoConfig video_configs = 4;
inline int AVChannel::_internal_video_configs_size() const {
  return _internal_video_configs().size();
}
inline int AVChannel::video_configs_size() const {
  return _internal_video_configs_size();
}
inline ::aasdk::proto::data::VideoConfig* PROTOBUF_NONNULL AVChannel::mutable_video_configs(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:aasdk.proto.data.AVChannel.video_configs)
  return _internal_mutable_video_configs()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::VideoConfig>* PROTOBUF_NONNULL AVChannel::mutable_video_configs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:aasdk.proto.data.AVChannel.video_configs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_video_configs();
}
inline const ::aasdk::proto::data::VideoConfig& AVChannel::video_configs(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.AVChannel.video_configs)
  return _internal_video_configs().Get(index);
}
inline ::aasdk::proto::data::VideoConfig* PROTOBUF_NONNULL AVChannel::add_video_configs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::aasdk::proto::data::VideoConfig* _add = _internal_mutable_video_configs()->Add();
  // @@protoc_insertion_point(field_add:aasdk.proto.data.AVChannel.video_configs)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::VideoConfig>& AVChannel::video_configs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:aasdk.proto.data.AVChannel.video_configs)
  return _internal_video_configs();
}
inline const ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::VideoConfig>&
AVChannel::_internal_video_configs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.video_configs_;
}
inline ::google::protobuf::RepeatedPtrField<::aasdk::proto::data::VideoConfig>* PROTOBUF_NONNULL
AVChannel::_internal_mutable_video_configs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.video_configs_;
}

// optional bool available_while_in_call = 5;
inline bool AVChannel::has_available_while_in_call() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void AVChannel::clear_available_while_in_call() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.available_while_in_call_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool AVChannel::available_while_in_call() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.data.AVChannel.available_while_in_call)
  return _internal_available_while_in_call();
}
inline void AVChannel::set_available_while_in_call(bool value) {
  _internal_set_available_while_in_call(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:aasdk.proto.data.AVChannel.available_while_in_call)
}
inline bool AVChannel::_internal_available_while_in_call() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.available_while_in_call_;
}
inline void AVChannel::_internal_set_available_while_in_call(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.available_while_in_call_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // AVChannelData_2eproto_2epb_2eh
