// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BluetoothChannelMessageIdsEnum.proto
// Protobuf C++ Version: 6.31.0

#include "BluetoothChannelMessageIdsEnum.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace ids {
template <typename>
PROTOBUF_CONSTEXPR BluetoothChannelMessage::BluetoothChannelMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(BluetoothChannelMessage_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct BluetoothChannelMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BluetoothChannelMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BluetoothChannelMessageDefaultTypeInternal() {}
  union {
    BluetoothChannelMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BluetoothChannelMessageDefaultTypeInternal _BluetoothChannelMessage_default_instance_;
}  // namespace ids
}  // namespace proto
}  // namespace aasdk
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_BluetoothChannelMessageIdsEnum_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_BluetoothChannelMessageIdsEnum_2eproto = nullptr;
const ::uint32_t
    TableStruct_BluetoothChannelMessageIdsEnum_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::ids::BluetoothChannelMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::ids::_BluetoothChannelMessage_default_instance_._instance,
};
const char descriptor_table_protodef_BluetoothChannelMessageIdsEnum_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n$BluetoothChannelMessageIdsEnum.proto\022\017"
    "aasdk.proto.ids\"k\n\027BluetoothChannelMessa"
    "ge\"P\n\004Enum\022\010\n\004NONE\020\000\022\025\n\017PAIRING_REQUEST\020"
    "\201\200\002\022\026\n\020PAIRING_RESPONSE\020\202\200\002\022\017\n\tAUTH_DATA"
    "\020\203\200\002"
};
static ::absl::once_flag descriptor_table_BluetoothChannelMessageIdsEnum_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_BluetoothChannelMessageIdsEnum_2eproto = {
    false,
    false,
    164,
    descriptor_table_protodef_BluetoothChannelMessageIdsEnum_2eproto,
    "BluetoothChannelMessageIdsEnum.proto",
    &descriptor_table_BluetoothChannelMessageIdsEnum_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_BluetoothChannelMessageIdsEnum_2eproto::offsets,
    file_level_enum_descriptors_BluetoothChannelMessageIdsEnum_2eproto,
    file_level_service_descriptors_BluetoothChannelMessageIdsEnum_2eproto,
};
namespace aasdk {
namespace proto {
namespace ids {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL BluetoothChannelMessage_Enum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_BluetoothChannelMessageIdsEnum_2eproto);
  return file_level_enum_descriptors_BluetoothChannelMessageIdsEnum_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t BluetoothChannelMessage_Enum_internal_data_[] = {
    65536u, 196608u, 32770u, 32769u, 32771u, };
// ===================================================================

class BluetoothChannelMessage::_Internal {
 public:
};

BluetoothChannelMessage::BluetoothChannelMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, BluetoothChannelMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.ids.BluetoothChannelMessage)
}
BluetoothChannelMessage::BluetoothChannelMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BluetoothChannelMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, BluetoothChannelMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BluetoothChannelMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:aasdk.proto.ids.BluetoothChannelMessage)
}

inline void* PROTOBUF_NONNULL BluetoothChannelMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BluetoothChannelMessage(arena);
}
constexpr auto BluetoothChannelMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(BluetoothChannelMessage),
                                            alignof(BluetoothChannelMessage));
}
constexpr auto BluetoothChannelMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BluetoothChannelMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BluetoothChannelMessage::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<BluetoothChannelMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BluetoothChannelMessage::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<BluetoothChannelMessage>(), &BluetoothChannelMessage::ByteSizeLong,
              &BluetoothChannelMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BluetoothChannelMessage, _impl_._cached_size_),
          false,
      },
      &BluetoothChannelMessage::kDescriptorMethods,
      &descriptor_table_BluetoothChannelMessageIdsEnum_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BluetoothChannelMessage_class_data_ =
        BluetoothChannelMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BluetoothChannelMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BluetoothChannelMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BluetoothChannelMessage_class_data_.tc_table);
  return BluetoothChannelMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
BluetoothChannelMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    BluetoothChannelMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::ids::BluetoothChannelMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata BluetoothChannelMessage::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ids
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_BluetoothChannelMessageIdsEnum_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
