// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ButtonCodeEnum.proto
// Protobuf C++ Version: 6.31.0

#ifndef ButtonCodeEnum_2eproto_2epb_2eh
#define ButtonCodeEnum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ButtonCodeEnum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ButtonCodeEnum_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ButtonCodeEnum_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace enums {
enum ButtonCode_Enum : int;
extern const uint32_t ButtonCode_Enum_internal_data_[];
class ButtonCode;
struct ButtonCodeDefaultTypeInternal;
extern ButtonCodeDefaultTypeInternal _ButtonCode_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ButtonCode_class_data_;
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::aasdk::proto::enums::ButtonCode_Enum_internal_data_>
    internal::EnumTraitsImpl::value<::aasdk::proto::enums::ButtonCode_Enum>;
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace enums {
enum ButtonCode_Enum : int {
  ButtonCode_Enum_NONE = 0,
  ButtonCode_Enum_MICROPHONE_2 = 1,
  ButtonCode_Enum_MENU = 2,
  ButtonCode_Enum_HOME = 3,
  ButtonCode_Enum_BACK = 4,
  ButtonCode_Enum_PHONE = 5,
  ButtonCode_Enum_CALL_END = 6,
  ButtonCode_Enum_UP = 19,
  ButtonCode_Enum_DOWN = 20,
  ButtonCode_Enum_LEFT = 21,
  ButtonCode_Enum_RIGHT = 22,
  ButtonCode_Enum_ENTER = 23,
  ButtonCode_Enum_MICROPHONE_1 = 84,
  ButtonCode_Enum_TOGGLE_PLAY = 85,
  ButtonCode_Enum_NEXT = 87,
  ButtonCode_Enum_PREV = 88,
  ButtonCode_Enum_PLAY = 126,
  ButtonCode_Enum_PAUSE = 127,
  ButtonCode_Enum_MUSIC = 209,
  ButtonCode_Enum_SCROLL_WHEEL = 65536,
  ButtonCode_Enum_MEDIA = 65537,
  ButtonCode_Enum_NAVIGATION = 65538,
  ButtonCode_Enum_RADIO = 65539,
  ButtonCode_Enum_TEL = 65540,
  ButtonCode_Enum_PRIMARY_BUTTON = 65541,
  ButtonCode_Enum_SECONDARY_BUTTON = 65542,
  ButtonCode_Enum_TERTIARY_BUTTON = 65543,
};

extern const uint32_t ButtonCode_Enum_internal_data_[];
inline constexpr ButtonCode_Enum ButtonCode_Enum_Enum_MIN =
    static_cast<ButtonCode_Enum>(0);
inline constexpr ButtonCode_Enum ButtonCode_Enum_Enum_MAX =
    static_cast<ButtonCode_Enum>(65543);
inline bool ButtonCode_Enum_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, ButtonCode_Enum_internal_data_);
}
inline constexpr int ButtonCode_Enum_Enum_ARRAYSIZE = 65543 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ButtonCode_Enum_descriptor();
template <typename T>
const ::std::string& ButtonCode_Enum_Name(T value) {
  static_assert(::std::is_same<T, ButtonCode_Enum>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Enum_Name().");
  return ::google::protobuf::internal::NameOfEnum(ButtonCode_Enum_descriptor(), value);
}
inline bool ButtonCode_Enum_Parse(
    ::absl::string_view name, ButtonCode_Enum* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ButtonCode_Enum>(ButtonCode_Enum_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class ButtonCode final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:aasdk.proto.enums.ButtonCode) */ {
 public:
  inline ButtonCode() : ButtonCode(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ButtonCode* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ButtonCode));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ButtonCode(::google::protobuf::internal::ConstantInitialized);

  inline ButtonCode(const ButtonCode& from) : ButtonCode(nullptr, from) {}
  inline ButtonCode(ButtonCode&& from) noexcept
      : ButtonCode(nullptr, ::std::move(from)) {}
  inline ButtonCode& operator=(const ButtonCode& from) {
    CopyFrom(from);
    return *this;
  }
  inline ButtonCode& operator=(ButtonCode&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ButtonCode& default_instance() {
    return *reinterpret_cast<const ButtonCode*>(
        &_ButtonCode_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ButtonCode& a, ButtonCode& b) { a.Swap(&b); }
  inline void Swap(ButtonCode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ButtonCode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ButtonCode* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<ButtonCode>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ButtonCode& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ButtonCode& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.enums.ButtonCode"; }

 protected:
  explicit ButtonCode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ButtonCode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ButtonCode& from);
  ButtonCode(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ButtonCode&& from) noexcept
      : ButtonCode(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Enum = ButtonCode_Enum;
  static constexpr Enum NONE = ButtonCode_Enum_NONE;
  static constexpr Enum MICROPHONE_2 = ButtonCode_Enum_MICROPHONE_2;
  static constexpr Enum MENU = ButtonCode_Enum_MENU;
  static constexpr Enum HOME = ButtonCode_Enum_HOME;
  static constexpr Enum BACK = ButtonCode_Enum_BACK;
  static constexpr Enum PHONE = ButtonCode_Enum_PHONE;
  static constexpr Enum CALL_END = ButtonCode_Enum_CALL_END;
  static constexpr Enum UP = ButtonCode_Enum_UP;
  static constexpr Enum DOWN = ButtonCode_Enum_DOWN;
  static constexpr Enum LEFT = ButtonCode_Enum_LEFT;
  static constexpr Enum RIGHT = ButtonCode_Enum_RIGHT;
  static constexpr Enum ENTER = ButtonCode_Enum_ENTER;
  static constexpr Enum MICROPHONE_1 = ButtonCode_Enum_MICROPHONE_1;
  static constexpr Enum TOGGLE_PLAY = ButtonCode_Enum_TOGGLE_PLAY;
  static constexpr Enum NEXT = ButtonCode_Enum_NEXT;
  static constexpr Enum PREV = ButtonCode_Enum_PREV;
  static constexpr Enum PLAY = ButtonCode_Enum_PLAY;
  static constexpr Enum PAUSE = ButtonCode_Enum_PAUSE;
  static constexpr Enum MUSIC = ButtonCode_Enum_MUSIC;
  static constexpr Enum SCROLL_WHEEL = ButtonCode_Enum_SCROLL_WHEEL;
  static constexpr Enum MEDIA = ButtonCode_Enum_MEDIA;
  static constexpr Enum NAVIGATION = ButtonCode_Enum_NAVIGATION;
  static constexpr Enum RADIO = ButtonCode_Enum_RADIO;
  static constexpr Enum TEL = ButtonCode_Enum_TEL;
  static constexpr Enum PRIMARY_BUTTON = ButtonCode_Enum_PRIMARY_BUTTON;
  static constexpr Enum SECONDARY_BUTTON = ButtonCode_Enum_SECONDARY_BUTTON;
  static constexpr Enum TERTIARY_BUTTON = ButtonCode_Enum_TERTIARY_BUTTON;
  static inline bool Enum_IsValid(int value) {
    return ButtonCode_Enum_IsValid(value);
  }
  static constexpr Enum Enum_MIN = ButtonCode_Enum_Enum_MIN;
  static constexpr Enum Enum_MAX = ButtonCode_Enum_Enum_MAX;
  static constexpr int Enum_ARRAYSIZE = ButtonCode_Enum_Enum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Enum_descriptor() {
    return ButtonCode_Enum_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Enum_Name(T value) {
    return ButtonCode_Enum_Name(value);
  }
  static inline bool Enum_Parse(
      ::absl::string_view name, Enum* PROTOBUF_NONNULL value) {
    return ButtonCode_Enum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:aasdk.proto.enums.ButtonCode)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ButtonCode& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_ButtonCodeEnum_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ButtonCode_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ButtonCode

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace enums
}  // namespace proto
}  // namespace aasdk


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::aasdk::proto::enums::ButtonCode_Enum> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::aasdk::proto::enums::ButtonCode_Enum>() {
  return ::aasdk::proto::enums::ButtonCode_Enum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ButtonCodeEnum_2eproto_2epb_2eh
