// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ButtonEventsData.proto
// Protobuf C++ Version: 6.31.0

#include "ButtonEventsData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace data {

inline constexpr ButtonEvents::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : button_events_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ButtonEvents::ButtonEvents(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ButtonEvents_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ButtonEventsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ButtonEventsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ButtonEventsDefaultTypeInternal() {}
  union {
    ButtonEvents _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ButtonEventsDefaultTypeInternal _ButtonEvents_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_ButtonEventsData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_ButtonEventsData_2eproto = nullptr;
const ::uint32_t
    TableStruct_ButtonEventsData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::ButtonEvents, _impl_.button_events_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::data::ButtonEvents)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::data::_ButtonEvents_default_instance_._instance,
};
const char descriptor_table_protodef_ButtonEventsData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026ButtonEventsData.proto\022\020aasdk.proto.da"
    "ta\032\025ButtonEventData.proto\"D\n\014ButtonEvent"
    "s\0224\n\rbutton_events\030\001 \003(\0132\035.aasdk.proto.d"
    "ata.ButtonEvent"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_ButtonEventsData_2eproto_deps[1] = {
        &::descriptor_table_ButtonEventData_2eproto,
};
static ::absl::once_flag descriptor_table_ButtonEventsData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ButtonEventsData_2eproto = {
    false,
    false,
    135,
    descriptor_table_protodef_ButtonEventsData_2eproto,
    "ButtonEventsData.proto",
    &descriptor_table_ButtonEventsData_2eproto_once,
    descriptor_table_ButtonEventsData_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_ButtonEventsData_2eproto::offsets,
    file_level_enum_descriptors_ButtonEventsData_2eproto,
    file_level_service_descriptors_ButtonEventsData_2eproto,
};
namespace aasdk {
namespace proto {
namespace data {
// ===================================================================

class ButtonEvents::_Internal {
 public:
};

void ButtonEvents::clear_button_events() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.button_events_.Clear();
}
ButtonEvents::ButtonEvents(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ButtonEvents_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.data.ButtonEvents)
}
PROTOBUF_NDEBUG_INLINE ButtonEvents::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::aasdk::proto::data::ButtonEvents& from_msg)
      : button_events_{visibility, arena, from.button_events_},
        _cached_size_{0} {}

ButtonEvents::ButtonEvents(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ButtonEvents& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ButtonEvents_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ButtonEvents* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:aasdk.proto.data.ButtonEvents)
}
PROTOBUF_NDEBUG_INLINE ButtonEvents::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : button_events_{visibility, arena},
        _cached_size_{0} {}

inline void ButtonEvents::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ButtonEvents::~ButtonEvents() {
  // @@protoc_insertion_point(destructor:aasdk.proto.data.ButtonEvents)
  SharedDtor(*this);
}
inline void ButtonEvents::SharedDtor(MessageLite& self) {
  ButtonEvents& this_ = static_cast<ButtonEvents&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ButtonEvents::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ButtonEvents(arena);
}
constexpr auto ButtonEvents::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ButtonEvents, _impl_.button_events_) +
          decltype(ButtonEvents::_impl_.button_events_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ButtonEvents), alignof(ButtonEvents), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ButtonEvents::PlacementNew_,
                                 sizeof(ButtonEvents),
                                 alignof(ButtonEvents));
  }
}
constexpr auto ButtonEvents::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ButtonEvents_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          ButtonEvents::IsInitializedImpl,
          &ButtonEvents::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ButtonEvents>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ButtonEvents::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ButtonEvents>(), &ButtonEvents::ByteSizeLong,
              &ButtonEvents::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ButtonEvents, _impl_._cached_size_),
          false,
      },
      &ButtonEvents::kDescriptorMethods,
      &descriptor_table_ButtonEventsData_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ButtonEvents_class_data_ =
        ButtonEvents::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ButtonEvents::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ButtonEvents_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ButtonEvents_class_data_.tc_table);
  return ButtonEvents_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
ButtonEvents::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ButtonEvents_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::data::ButtonEvents>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .aasdk.proto.data.ButtonEvent button_events = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ButtonEvents, _impl_.button_events_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .aasdk.proto.data.ButtonEvent button_events = 1;
    {PROTOBUF_FIELD_OFFSET(ButtonEvents, _impl_.button_events_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aasdk::proto::data::ButtonEvent>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ButtonEvents::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.data.ButtonEvents)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.button_events_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ButtonEvents::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ButtonEvents& this_ = static_cast<const ButtonEvents&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ButtonEvents::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ButtonEvents& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.data.ButtonEvents)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .aasdk.proto.data.ButtonEvent button_events = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_button_events_size());
       i < n; i++) {
    const auto& repfield = this_._internal_button_events().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.data.ButtonEvents)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ButtonEvents::ByteSizeLong(const MessageLite& base) {
  const ButtonEvents& this_ = static_cast<const ButtonEvents&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ButtonEvents::ByteSizeLong() const {
  const ButtonEvents& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aasdk.proto.data.ButtonEvents)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .aasdk.proto.data.ButtonEvent button_events = 1;
    {
      total_size += 1UL * this_._internal_button_events_size();
      for (const auto& msg : this_._internal_button_events()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ButtonEvents::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ButtonEvents*>(&to_msg);
  auto& from = static_cast<const ButtonEvents&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.data.ButtonEvents)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_button_events()->MergeFrom(
      from._internal_button_events());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ButtonEvents::CopyFrom(const ButtonEvents& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.data.ButtonEvents)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ButtonEvents::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const ButtonEvents&>(msg);
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_button_events()))
    return false;
  return true;
}

void ButtonEvents::InternalSwap(ButtonEvents* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.button_events_.InternalSwap(&other->_impl_.button_events_);
}

::google::protobuf::Metadata ButtonEvents::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_ButtonEventsData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
