// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: LightData.proto
// Protobuf C++ Version: 6.31.0

#include "LightData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace data {

inline constexpr Light::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        headlight_{static_cast< ::aasdk::proto::enums::HeadlightStatus_Enum >(0)},
        indicator_{static_cast< ::aasdk::proto::enums::IndicatorStatus_Enum >(0)},
        hazard_light_on_{false} {}

template <typename>
PROTOBUF_CONSTEXPR Light::Light(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Light_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LightDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LightDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LightDefaultTypeInternal() {}
  union {
    Light _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LightDefaultTypeInternal _Light_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_LightData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_LightData_2eproto = nullptr;
const ::uint32_t
    TableStruct_LightData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::Light, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::Light, _impl_.headlight_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::Light, _impl_.indicator_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::Light, _impl_.hazard_light_on_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::data::Light)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::data::_Light_default_instance_._instance,
};
const char descriptor_table_protodef_LightData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017LightData.proto\022\020aasdk.proto.data\032\031Hea"
    "dlightStatusEnum.proto\032\031IndicatorStatusE"
    "num.proto\"\230\001\n\005Light\022:\n\theadlight\030\001 \002(\0162\'"
    ".aasdk.proto.enums.HeadlightStatus.Enum\022"
    ":\n\tindicator\030\002 \002(\0162\'.aasdk.proto.enums.I"
    "ndicatorStatus.Enum\022\027\n\017hazard_light_on\030\003"
    " \002(\010"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_LightData_2eproto_deps[2] = {
        &::descriptor_table_HeadlightStatusEnum_2eproto,
        &::descriptor_table_IndicatorStatusEnum_2eproto,
};
static ::absl::once_flag descriptor_table_LightData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_LightData_2eproto = {
    false,
    false,
    244,
    descriptor_table_protodef_LightData_2eproto,
    "LightData.proto",
    &descriptor_table_LightData_2eproto_once,
    descriptor_table_LightData_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_LightData_2eproto::offsets,
    file_level_enum_descriptors_LightData_2eproto,
    file_level_service_descriptors_LightData_2eproto,
};
namespace aasdk {
namespace proto {
namespace data {
// ===================================================================

class Light::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Light>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Light, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

Light::Light(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Light_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.data.Light)
}
Light::Light(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Light& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Light_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Light::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Light::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, headlight_),
           0,
           offsetof(Impl_, hazard_light_on_) -
               offsetof(Impl_, headlight_) +
               sizeof(Impl_::hazard_light_on_));
}
Light::~Light() {
  // @@protoc_insertion_point(destructor:aasdk.proto.data.Light)
  SharedDtor(*this);
}
inline void Light::SharedDtor(MessageLite& self) {
  Light& this_ = static_cast<Light&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Light::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Light(arena);
}
constexpr auto Light::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Light),
                                            alignof(Light));
}
constexpr auto Light::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Light_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          Light::IsInitializedImpl,
          &Light::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Light>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Light::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Light>(), &Light::ByteSizeLong,
              &Light::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Light, _impl_._cached_size_),
          false,
      },
      &Light::kDescriptorMethods,
      &descriptor_table_LightData_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Light_class_data_ =
        Light::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Light::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Light_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Light_class_data_.tc_table);
  return Light_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2>
Light::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Light, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Light_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::data::Light>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required .aasdk.proto.enums.HeadlightStatus.Enum headlight = 1;
    {::_pbi::TcParser::FastEr0S1,
     {8, 0, 3, PROTOBUF_FIELD_OFFSET(Light, _impl_.headlight_)}},
    // required .aasdk.proto.enums.IndicatorStatus.Enum indicator = 2;
    {::_pbi::TcParser::FastEr0S1,
     {16, 1, 3, PROTOBUF_FIELD_OFFSET(Light, _impl_.indicator_)}},
    // required bool hazard_light_on = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Light, _impl_.hazard_light_on_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Light, _impl_.hazard_light_on_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required .aasdk.proto.enums.HeadlightStatus.Enum headlight = 1;
    {PROTOBUF_FIELD_OFFSET(Light, _impl_.headlight_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // required .aasdk.proto.enums.IndicatorStatus.Enum indicator = 2;
    {PROTOBUF_FIELD_OFFSET(Light, _impl_.indicator_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // required bool hazard_light_on = 3;
    {PROTOBUF_FIELD_OFFSET(Light, _impl_.hazard_light_on_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {0, 3},
      {0, 3},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Light::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.data.Light)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    ::memset(&_impl_.headlight_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.hazard_light_on_) -
        reinterpret_cast<char*>(&_impl_.headlight_)) + sizeof(_impl_.hazard_light_on_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Light::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Light& this_ = static_cast<const Light&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Light::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Light& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.data.Light)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required .aasdk.proto.enums.HeadlightStatus.Enum headlight = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_headlight(), target);
  }

  // required .aasdk.proto.enums.IndicatorStatus.Enum indicator = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this_._internal_indicator(), target);
  }

  // required bool hazard_light_on = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this_._internal_hazard_light_on(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.data.Light)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Light::ByteSizeLong(const MessageLite& base) {
  const Light& this_ = static_cast<const Light&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Light::ByteSizeLong() const {
  const Light& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aasdk.proto.data.Light)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000004u & cached_has_bits) * 2;
  if ((cached_has_bits & 0x00000003u) != 0) {
    // required .aasdk.proto.enums.HeadlightStatus.Enum headlight = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_headlight());
    }
    // required .aasdk.proto.enums.IndicatorStatus.Enum indicator = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_indicator());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Light::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Light*>(&to_msg);
  auto& from = static_cast<const Light&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.data.Light)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.headlight_ = from._impl_.headlight_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.indicator_ = from._impl_.indicator_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.hazard_light_on_ = from._impl_.hazard_light_on_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Light::CopyFrom(const Light& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.data.Light)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Light::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Light&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void Light::InternalSwap(Light* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Light, _impl_.hazard_light_on_)
      + sizeof(Light::_impl_.hazard_light_on_)
      - PROTOBUF_FIELD_OFFSET(Light, _impl_.headlight_)>(
          reinterpret_cast<char*>(&_impl_.headlight_),
          reinterpret_cast<char*>(&other->_impl_.headlight_));
}

::google::protobuf::Metadata Light::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_LightData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
