// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NavigationStatusMessage.proto
// Protobuf C++ Version: 6.31.0

#ifndef NavigationStatusMessage_2eproto_2epb_2eh
#define NavigationStatusMessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_NavigationStatusMessage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_NavigationStatusMessage_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_NavigationStatusMessage_2eproto;
}  // extern "C"
namespace aasdk {
namespace proto {
namespace messages {
enum NavigationStatus_Enum : int;
extern const uint32_t NavigationStatus_Enum_internal_data_[];
class NavigationStatus;
struct NavigationStatusDefaultTypeInternal;
extern NavigationStatusDefaultTypeInternal _NavigationStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NavigationStatus_class_data_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::aasdk::proto::messages::NavigationStatus_Enum_internal_data_>
    internal::EnumTraitsImpl::value<::aasdk::proto::messages::NavigationStatus_Enum>;
}  // namespace protobuf
}  // namespace google

namespace aasdk {
namespace proto {
namespace messages {
enum NavigationStatus_Enum : int {
  NavigationStatus_Enum_UNAVAILABLE = 0,
  NavigationStatus_Enum_ACTIVE = 1,
  NavigationStatus_Enum_INACTIVE = 2,
  NavigationStatus_Enum_REROUTING = 3,
};

extern const uint32_t NavigationStatus_Enum_internal_data_[];
inline constexpr NavigationStatus_Enum NavigationStatus_Enum_Enum_MIN =
    static_cast<NavigationStatus_Enum>(0);
inline constexpr NavigationStatus_Enum NavigationStatus_Enum_Enum_MAX =
    static_cast<NavigationStatus_Enum>(3);
inline bool NavigationStatus_Enum_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int NavigationStatus_Enum_Enum_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL NavigationStatus_Enum_descriptor();
template <typename T>
const ::std::string& NavigationStatus_Enum_Name(T value) {
  static_assert(::std::is_same<T, NavigationStatus_Enum>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Enum_Name().");
  return NavigationStatus_Enum_Name(static_cast<NavigationStatus_Enum>(value));
}
template <>
inline const ::std::string& NavigationStatus_Enum_Name(NavigationStatus_Enum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<NavigationStatus_Enum_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool NavigationStatus_Enum_Parse(
    ::absl::string_view name, NavigationStatus_Enum* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<NavigationStatus_Enum>(NavigationStatus_Enum_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class NavigationStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:aasdk.proto.messages.NavigationStatus) */ {
 public:
  inline NavigationStatus() : NavigationStatus(nullptr) {}
  ~NavigationStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NavigationStatus* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NavigationStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NavigationStatus(::google::protobuf::internal::ConstantInitialized);

  inline NavigationStatus(const NavigationStatus& from) : NavigationStatus(nullptr, from) {}
  inline NavigationStatus(NavigationStatus&& from) noexcept
      : NavigationStatus(nullptr, ::std::move(from)) {}
  inline NavigationStatus& operator=(const NavigationStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline NavigationStatus& operator=(NavigationStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NavigationStatus& default_instance() {
    return *reinterpret_cast<const NavigationStatus*>(
        &_NavigationStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NavigationStatus& a, NavigationStatus& b) { a.Swap(&b); }
  inline void Swap(NavigationStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NavigationStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NavigationStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<NavigationStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NavigationStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NavigationStatus& from) { NavigationStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(NavigationStatus* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "aasdk.proto.messages.NavigationStatus"; }

 protected:
  explicit NavigationStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NavigationStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NavigationStatus& from);
  NavigationStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NavigationStatus&& from) noexcept
      : NavigationStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Enum = NavigationStatus_Enum;
  static constexpr Enum UNAVAILABLE = NavigationStatus_Enum_UNAVAILABLE;
  static constexpr Enum ACTIVE = NavigationStatus_Enum_ACTIVE;
  static constexpr Enum INACTIVE = NavigationStatus_Enum_INACTIVE;
  static constexpr Enum REROUTING = NavigationStatus_Enum_REROUTING;
  static inline bool Enum_IsValid(int value) {
    return NavigationStatus_Enum_IsValid(value);
  }
  static constexpr Enum Enum_MIN = NavigationStatus_Enum_Enum_MIN;
  static constexpr Enum Enum_MAX = NavigationStatus_Enum_Enum_MAX;
  static constexpr int Enum_ARRAYSIZE = NavigationStatus_Enum_Enum_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Enum_descriptor() {
    return NavigationStatus_Enum_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Enum_Name(T value) {
    return NavigationStatus_Enum_Name(value);
  }
  static inline bool Enum_Parse(
      ::absl::string_view name, Enum* PROTOBUF_NONNULL value) {
    return NavigationStatus_Enum_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // required .aasdk.proto.messages.NavigationStatus.Enum status = 1;
  bool has_status() const;
  void clear_status() ;
  ::aasdk::proto::messages::NavigationStatus_Enum status() const;
  void set_status(::aasdk::proto::messages::NavigationStatus_Enum value);

  private:
  ::aasdk::proto::messages::NavigationStatus_Enum _internal_status() const;
  void _internal_set_status(::aasdk::proto::messages::NavigationStatus_Enum value);

  public:
  // @@protoc_insertion_point(class_scope:aasdk.proto.messages.NavigationStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const NavigationStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NavigationStatusMessage_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NavigationStatus_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NavigationStatus

// required .aasdk.proto.messages.NavigationStatus.Enum status = 1;
inline bool NavigationStatus::has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void NavigationStatus::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::aasdk::proto::messages::NavigationStatus_Enum NavigationStatus::status() const {
  // @@protoc_insertion_point(field_get:aasdk.proto.messages.NavigationStatus.status)
  return _internal_status();
}
inline void NavigationStatus::set_status(::aasdk::proto::messages::NavigationStatus_Enum value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:aasdk.proto.messages.NavigationStatus.status)
}
inline ::aasdk::proto::messages::NavigationStatus_Enum NavigationStatus::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::aasdk::proto::messages::NavigationStatus_Enum>(_impl_.status_);
}
inline void NavigationStatus::_internal_set_status(::aasdk::proto::messages::NavigationStatus_Enum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::aasdk::proto::messages::NavigationStatus_Enum_internal_data_));
                                          _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace proto
}  // namespace aasdk


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::aasdk::proto::messages::NavigationStatus_Enum> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::aasdk::proto::messages::NavigationStatus_Enum>() {
  return ::aasdk::proto::messages::NavigationStatus_Enum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // NavigationStatusMessage_2eproto_2epb_2eh
