// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NavigationTurnEventMessage.proto
// Protobuf C++ Version: 6.31.0

#include "NavigationTurnEventMessage.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace messages {

inline constexpr NavigationTurnEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        street_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        turnimage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        maneuverdirection_{static_cast< ::aasdk::proto::enums::ManeuverDirection_Enum >(0)},
        maneuvertype_{static_cast< ::aasdk::proto::enums::ManeuverType_Enum >(0)},
        roundaboutexitnumber_{0u},
        roundaboutexitangle_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR NavigationTurnEvent::NavigationTurnEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NavigationTurnEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NavigationTurnEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NavigationTurnEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NavigationTurnEventDefaultTypeInternal() {}
  union {
    NavigationTurnEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NavigationTurnEventDefaultTypeInternal _NavigationTurnEvent_default_instance_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_NavigationTurnEventMessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_NavigationTurnEventMessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_NavigationTurnEventMessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::NavigationTurnEvent, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::NavigationTurnEvent, _impl_.street_name_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::NavigationTurnEvent, _impl_.maneuverdirection_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::NavigationTurnEvent, _impl_.maneuvertype_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::NavigationTurnEvent, _impl_.turnimage_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::NavigationTurnEvent, _impl_.roundaboutexitnumber_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::messages::NavigationTurnEvent, _impl_.roundaboutexitangle_),
        0,
        2,
        3,
        1,
        4,
        5,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::messages::NavigationTurnEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::messages::_NavigationTurnEvent_default_instance_._instance,
};
const char descriptor_table_protodef_NavigationTurnEventMessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n NavigationTurnEventMessage.proto\022\024aasd"
    "k.proto.messages\032\026ManeuverTypeEnum.proto"
    "\032\033ManeuverDirectionEnum.proto\"\372\001\n\023Naviga"
    "tionTurnEvent\022\023\n\013street_name\030\001 \002(\t\022D\n\021ma"
    "neuverDirection\030\002 \002(\0162).aasdk.proto.enum"
    "s.ManeuverDirection.Enum\022:\n\014maneuverType"
    "\030\003 \002(\0162$.aasdk.proto.enums.ManeuverType."
    "Enum\022\021\n\tturnImage\030\004 \002(\014\022\034\n\024roundaboutExi"
    "tNumber\030\005 \002(\r\022\033\n\023roundaboutExitAngle\030\006 \002"
    "(\r"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_NavigationTurnEventMessage_2eproto_deps[2] = {
        &::descriptor_table_ManeuverDirectionEnum_2eproto,
        &::descriptor_table_ManeuverTypeEnum_2eproto,
};
static ::absl::once_flag descriptor_table_NavigationTurnEventMessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_NavigationTurnEventMessage_2eproto = {
    false,
    false,
    362,
    descriptor_table_protodef_NavigationTurnEventMessage_2eproto,
    "NavigationTurnEventMessage.proto",
    &descriptor_table_NavigationTurnEventMessage_2eproto_once,
    descriptor_table_NavigationTurnEventMessage_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_NavigationTurnEventMessage_2eproto::offsets,
    file_level_enum_descriptors_NavigationTurnEventMessage_2eproto,
    file_level_service_descriptors_NavigationTurnEventMessage_2eproto,
};
namespace aasdk {
namespace proto {
namespace messages {
// ===================================================================

class NavigationTurnEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NavigationTurnEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000003f) ^ 0x0000003f) != 0;
  }
};

NavigationTurnEvent::NavigationTurnEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NavigationTurnEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.messages.NavigationTurnEvent)
}
PROTOBUF_NDEBUG_INLINE NavigationTurnEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::aasdk::proto::messages::NavigationTurnEvent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        street_name_(arena, from.street_name_),
        turnimage_(arena, from.turnimage_) {}

NavigationTurnEvent::NavigationTurnEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NavigationTurnEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NavigationTurnEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NavigationTurnEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, maneuverdirection_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, maneuverdirection_),
           offsetof(Impl_, roundaboutexitangle_) -
               offsetof(Impl_, maneuverdirection_) +
               sizeof(Impl_::roundaboutexitangle_));

  // @@protoc_insertion_point(copy_constructor:aasdk.proto.messages.NavigationTurnEvent)
}
PROTOBUF_NDEBUG_INLINE NavigationTurnEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        street_name_(arena),
        turnimage_(arena) {}

inline void NavigationTurnEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, maneuverdirection_),
           0,
           offsetof(Impl_, roundaboutexitangle_) -
               offsetof(Impl_, maneuverdirection_) +
               sizeof(Impl_::roundaboutexitangle_));
}
NavigationTurnEvent::~NavigationTurnEvent() {
  // @@protoc_insertion_point(destructor:aasdk.proto.messages.NavigationTurnEvent)
  SharedDtor(*this);
}
inline void NavigationTurnEvent::SharedDtor(MessageLite& self) {
  NavigationTurnEvent& this_ = static_cast<NavigationTurnEvent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.street_name_.Destroy();
  this_._impl_.turnimage_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NavigationTurnEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NavigationTurnEvent(arena);
}
constexpr auto NavigationTurnEvent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NavigationTurnEvent),
                                            alignof(NavigationTurnEvent));
}
constexpr auto NavigationTurnEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NavigationTurnEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          NavigationTurnEvent::IsInitializedImpl,
          &NavigationTurnEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NavigationTurnEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NavigationTurnEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NavigationTurnEvent>(), &NavigationTurnEvent::ByteSizeLong,
              &NavigationTurnEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_._cached_size_),
          false,
      },
      &NavigationTurnEvent::kDescriptorMethods,
      &descriptor_table_NavigationTurnEventMessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NavigationTurnEvent_class_data_ =
        NavigationTurnEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NavigationTurnEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NavigationTurnEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NavigationTurnEvent_class_data_.tc_table);
  return NavigationTurnEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 60, 2>
NavigationTurnEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    NavigationTurnEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::messages::NavigationTurnEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required string street_name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.street_name_)}},
    // required .aasdk.proto.enums.ManeuverDirection.Enum maneuverDirection = 2;
    {::_pbi::TcParser::FastEr0S1,
     {16, 2, 3, PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.maneuverdirection_)}},
    // required .aasdk.proto.enums.ManeuverType.Enum maneuverType = 3;
    {::_pbi::TcParser::FastEvS1,
     {24, 3, 1, PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.maneuvertype_)}},
    // required bytes turnImage = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.turnimage_)}},
    // required uint32 roundaboutExitNumber = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NavigationTurnEvent, _impl_.roundaboutexitnumber_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.roundaboutexitnumber_)}},
    // required uint32 roundaboutExitAngle = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NavigationTurnEvent, _impl_.roundaboutexitangle_), 5>(),
     {48, 5, 0, PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.roundaboutexitangle_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // required string street_name = 1;
    {PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.street_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required .aasdk.proto.enums.ManeuverDirection.Enum maneuverDirection = 2;
    {PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.maneuverdirection_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // required .aasdk.proto.enums.ManeuverType.Enum maneuverType = 3;
    {PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.maneuvertype_), _Internal::kHasBitsOffset + 3, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // required bytes turnImage = 4;
    {PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.turnimage_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // required uint32 roundaboutExitNumber = 5;
    {PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.roundaboutexitnumber_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // required uint32 roundaboutExitAngle = 6;
    {PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.roundaboutexitangle_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  {{
      {0, 3},
      {::_pbi::FieldAuxEnumData{}, ::aasdk::proto::enums::ManeuverType_Enum_internal_data_},
  }},
  {{
    "\50\13\0\0\0\0\0\0"
    "aasdk.proto.messages.NavigationTurnEvent"
    "street_name"
  }},
};
PROTOBUF_NOINLINE void NavigationTurnEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.messages.NavigationTurnEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.street_name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.turnimage_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x0000003cu) != 0) {
    ::memset(&_impl_.maneuverdirection_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.roundaboutexitangle_) -
        reinterpret_cast<char*>(&_impl_.maneuverdirection_)) + sizeof(_impl_.roundaboutexitangle_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NavigationTurnEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NavigationTurnEvent& this_ = static_cast<const NavigationTurnEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NavigationTurnEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NavigationTurnEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.messages.NavigationTurnEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required string street_name = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_street_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "aasdk.proto.messages.NavigationTurnEvent.street_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // required .aasdk.proto.enums.ManeuverDirection.Enum maneuverDirection = 2;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this_._internal_maneuverdirection(), target);
  }

  // required .aasdk.proto.enums.ManeuverType.Enum maneuverType = 3;
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this_._internal_maneuvertype(), target);
  }

  // required bytes turnImage = 4;
  if ((cached_has_bits & 0x00000002u) != 0) {
    const ::std::string& _s = this_._internal_turnimage();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  // required uint32 roundaboutExitNumber = 5;
  if ((cached_has_bits & 0x00000010u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this_._internal_roundaboutexitnumber(), target);
  }

  // required uint32 roundaboutExitAngle = 6;
  if ((cached_has_bits & 0x00000020u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this_._internal_roundaboutexitangle(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.messages.NavigationTurnEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NavigationTurnEvent::ByteSizeLong(const MessageLite& base) {
  const NavigationTurnEvent& this_ = static_cast<const NavigationTurnEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NavigationTurnEvent::ByteSizeLong() const {
  const NavigationTurnEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aasdk.proto.messages.NavigationTurnEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000003fu) != 0) {
    // required string street_name = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_street_name());
    }
    // required bytes turnImage = 4;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_turnimage());
    }
    // required .aasdk.proto.enums.ManeuverDirection.Enum maneuverDirection = 2;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_maneuverdirection());
    }
    // required .aasdk.proto.enums.ManeuverType.Enum maneuverType = 3;
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_maneuvertype());
    }
    // required uint32 roundaboutExitNumber = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_roundaboutexitnumber());
    }
    // required uint32 roundaboutExitAngle = 6;
    if ((cached_has_bits & 0x00000020u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_roundaboutexitangle());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NavigationTurnEvent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NavigationTurnEvent*>(&to_msg);
  auto& from = static_cast<const NavigationTurnEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.messages.NavigationTurnEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000003fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_street_name(from._internal_street_name());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_internal_set_turnimage(from._internal_turnimage());
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.maneuverdirection_ = from._impl_.maneuverdirection_;
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _this->_impl_.maneuvertype_ = from._impl_.maneuvertype_;
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _this->_impl_.roundaboutexitnumber_ = from._impl_.roundaboutexitnumber_;
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      _this->_impl_.roundaboutexitangle_ = from._impl_.roundaboutexitangle_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NavigationTurnEvent::CopyFrom(const NavigationTurnEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.messages.NavigationTurnEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NavigationTurnEvent::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const NavigationTurnEvent&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void NavigationTurnEvent::InternalSwap(NavigationTurnEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.street_name_, &other->_impl_.street_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.turnimage_, &other->_impl_.turnimage_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.roundaboutexitangle_)
      + sizeof(NavigationTurnEvent::_impl_.roundaboutexitangle_)
      - PROTOBUF_FIELD_OFFSET(NavigationTurnEvent, _impl_.maneuverdirection_)>(
          reinterpret_cast<char*>(&_impl_.maneuverdirection_),
          reinterpret_cast<char*>(&other->_impl_.maneuverdirection_));
}

::google::protobuf::Metadata NavigationTurnEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_NavigationTurnEventMessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
