// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SensorTypeEnum.proto
// Protobuf C++ Version: 6.31.0

#include "SensorTypeEnum.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace enums {
template <typename>
PROTOBUF_CONSTEXPR SensorType::SensorType(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(SensorType_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct SensorTypeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SensorTypeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SensorTypeDefaultTypeInternal() {}
  union {
    SensorType _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SensorTypeDefaultTypeInternal _SensorType_default_instance_;
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_SensorTypeEnum_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_SensorTypeEnum_2eproto = nullptr;
const ::uint32_t
    TableStruct_SensorTypeEnum_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::enums::SensorType)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::enums::_SensorType_default_instance_._instance,
};
const char descriptor_table_protodef_SensorTypeEnum_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024SensorTypeEnum.proto\022\021aasdk.proto.enum"
    "s\"\274\002\n\nSensorType\"\255\002\n\004Enum\022\010\n\004NONE\020\000\022\014\n\010L"
    "OCATION\020\001\022\013\n\007COMPASS\020\002\022\r\n\tCAR_SPEED\020\003\022\007\n"
    "\003RPM\020\004\022\014\n\010ODOMETER\020\005\022\016\n\nFUEL_LEVEL\020\006\022\021\n\r"
    "PARKING_BRAKE\020\007\022\010\n\004GEAR\020\010\022\017\n\013DIAGNOSTICS"
    "\020\t\022\016\n\nNIGHT_DATA\020\n\022\017\n\013ENVIRONMENT\020\013\022\010\n\004H"
    "VAC\020\014\022\022\n\016DRIVING_STATUS\020\r\022\021\n\rDEAD_RECONI"
    "NG\020\016\022\r\n\tPASSENGER\020\017\022\010\n\004DOOR\020\020\022\t\n\005LIGHT\020\021"
    "\022\010\n\004TIRE\020\022\022\t\n\005ACCEL\020\023\022\010\n\004GYRO\020\024\022\007\n\003GPS\020\025"
};
static ::absl::once_flag descriptor_table_SensorTypeEnum_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SensorTypeEnum_2eproto = {
    false,
    false,
    360,
    descriptor_table_protodef_SensorTypeEnum_2eproto,
    "SensorTypeEnum.proto",
    &descriptor_table_SensorTypeEnum_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_SensorTypeEnum_2eproto::offsets,
    file_level_enum_descriptors_SensorTypeEnum_2eproto,
    file_level_service_descriptors_SensorTypeEnum_2eproto,
};
namespace aasdk {
namespace proto {
namespace enums {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SensorType_Enum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_SensorTypeEnum_2eproto);
  return file_level_enum_descriptors_SensorTypeEnum_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SensorType_Enum_internal_data_[] = {
    1441792u, 0u, };
// ===================================================================

class SensorType::_Internal {
 public:
};

SensorType::SensorType(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SensorType_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.enums.SensorType)
}
SensorType::SensorType(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SensorType& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, SensorType_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SensorType* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:aasdk.proto.enums.SensorType)
}

inline void* PROTOBUF_NONNULL SensorType::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SensorType(arena);
}
constexpr auto SensorType::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SensorType),
                                            alignof(SensorType));
}
constexpr auto SensorType::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SensorType_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SensorType::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SensorType>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SensorType::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SensorType>(), &SensorType::ByteSizeLong,
              &SensorType::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SensorType, _impl_._cached_size_),
          false,
      },
      &SensorType::kDescriptorMethods,
      &descriptor_table_SensorTypeEnum_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SensorType_class_data_ =
        SensorType::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SensorType::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SensorType_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SensorType_class_data_.tc_table);
  return SensorType_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
SensorType::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SensorType_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::enums::SensorType>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata SensorType::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_SensorTypeEnum_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
