// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TouchEventData.proto
// Protobuf C++ Version: 6.31.0

#include "TouchEventData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace aasdk {
namespace proto {
namespace data {

inline constexpr TouchEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        touch_location_{},
        action_index_{0u},
        touch_action_{static_cast< ::aasdk::proto::enums::TouchAction_Enum >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR TouchEvent::TouchEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TouchEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TouchEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TouchEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TouchEventDefaultTypeInternal() {}
  union {
    TouchEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TouchEventDefaultTypeInternal _TouchEvent_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_TouchEventData_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_TouchEventData_2eproto = nullptr;
const ::uint32_t
    TableStruct_TouchEventData_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::TouchEvent, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::TouchEvent, _impl_.touch_location_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::TouchEvent, _impl_.action_index_),
        PROTOBUF_FIELD_OFFSET(::aasdk::proto::data::TouchEvent, _impl_.touch_action_),
        ~0u,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::aasdk::proto::data::TouchEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::aasdk::proto::data::_TouchEvent_default_instance_._instance,
};
const char descriptor_table_protodef_TouchEventData_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024TouchEventData.proto\022\020aasdk.proto.data"
    "\032\027TouchLocationData.proto\032\025TouchActionEn"
    "um.proto\"\226\001\n\nTouchEvent\0227\n\016touch_locatio"
    "n\030\001 \003(\0132\037.aasdk.proto.data.TouchLocation"
    "\022\024\n\014action_index\030\002 \001(\r\0229\n\014touch_action\030\003"
    " \002(\0162#.aasdk.proto.enums.TouchAction.Enu"
    "m"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_TouchEventData_2eproto_deps[2] = {
        &::descriptor_table_TouchActionEnum_2eproto,
        &::descriptor_table_TouchLocationData_2eproto,
};
static ::absl::once_flag descriptor_table_TouchEventData_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_TouchEventData_2eproto = {
    false,
    false,
    241,
    descriptor_table_protodef_TouchEventData_2eproto,
    "TouchEventData.proto",
    &descriptor_table_TouchEventData_2eproto_once,
    descriptor_table_TouchEventData_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_TouchEventData_2eproto::offsets,
    file_level_enum_descriptors_TouchEventData_2eproto,
    file_level_service_descriptors_TouchEventData_2eproto,
};
namespace aasdk {
namespace proto {
namespace data {
// ===================================================================

class TouchEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TouchEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000002) ^ 0x00000002) != 0;
  }
};

void TouchEvent::clear_touch_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.touch_location_.Clear();
}
TouchEvent::TouchEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TouchEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:aasdk.proto.data.TouchEvent)
}
PROTOBUF_NDEBUG_INLINE TouchEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::aasdk::proto::data::TouchEvent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        touch_location_{visibility, arena, from.touch_location_} {}

TouchEvent::TouchEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TouchEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TouchEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TouchEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, action_index_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, action_index_),
           offsetof(Impl_, touch_action_) -
               offsetof(Impl_, action_index_) +
               sizeof(Impl_::touch_action_));

  // @@protoc_insertion_point(copy_constructor:aasdk.proto.data.TouchEvent)
}
PROTOBUF_NDEBUG_INLINE TouchEvent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        touch_location_{visibility, arena} {}

inline void TouchEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, action_index_),
           0,
           offsetof(Impl_, touch_action_) -
               offsetof(Impl_, action_index_) +
               sizeof(Impl_::touch_action_));
}
TouchEvent::~TouchEvent() {
  // @@protoc_insertion_point(destructor:aasdk.proto.data.TouchEvent)
  SharedDtor(*this);
}
inline void TouchEvent::SharedDtor(MessageLite& self) {
  TouchEvent& this_ = static_cast<TouchEvent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TouchEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TouchEvent(arena);
}
constexpr auto TouchEvent::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.touch_location_) +
          decltype(TouchEvent::_impl_.touch_location_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(TouchEvent), alignof(TouchEvent), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TouchEvent::PlacementNew_,
                                 sizeof(TouchEvent),
                                 alignof(TouchEvent));
  }
}
constexpr auto TouchEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TouchEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          TouchEvent::IsInitializedImpl,
          &TouchEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TouchEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TouchEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TouchEvent>(), &TouchEvent::ByteSizeLong,
              &TouchEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_._cached_size_),
          false,
      },
      &TouchEvent::kDescriptorMethods,
      &descriptor_table_TouchEventData_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TouchEvent_class_data_ =
        TouchEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TouchEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TouchEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TouchEvent_class_data_.tc_table);
  return TouchEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2>
TouchEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    TouchEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::aasdk::proto::data::TouchEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .aasdk.proto.data.TouchLocation touch_location = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.touch_location_)}},
    // optional uint32 action_index = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TouchEvent, _impl_.action_index_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.action_index_)}},
    // required .aasdk.proto.enums.TouchAction.Enum touch_action = 3;
    {::_pbi::TcParser::FastEvS1,
     {24, 1, 1, PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.touch_action_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .aasdk.proto.data.TouchLocation touch_location = 1;
    {PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.touch_location_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional uint32 action_index = 2;
    {PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.action_index_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // required .aasdk.proto.enums.TouchAction.Enum touch_action = 3;
    {PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.touch_action_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::aasdk::proto::data::TouchLocation>()},
      {::_pbi::FieldAuxEnumData{}, ::aasdk::proto::enums::TouchAction_Enum_internal_data_},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void TouchEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:aasdk.proto.data.TouchEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.touch_location_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.action_index_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.touch_action_) -
        reinterpret_cast<char*>(&_impl_.action_index_)) + sizeof(_impl_.touch_action_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TouchEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TouchEvent& this_ = static_cast<const TouchEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TouchEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TouchEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:aasdk.proto.data.TouchEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .aasdk.proto.data.TouchLocation touch_location = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_touch_location_size());
       i < n; i++) {
    const auto& repfield = this_._internal_touch_location().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 action_index = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_action_index(), target);
  }

  // required .aasdk.proto.enums.TouchAction.Enum touch_action = 3;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this_._internal_touch_action(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aasdk.proto.data.TouchEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TouchEvent::ByteSizeLong(const MessageLite& base) {
  const TouchEvent& this_ = static_cast<const TouchEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TouchEvent::ByteSizeLong() const {
  const TouchEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:aasdk.proto.data.TouchEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .aasdk.proto.data.TouchLocation touch_location = 1;
    {
      total_size += 1UL * this_._internal_touch_location_size();
      for (const auto& msg : this_._internal_touch_location()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
   {
    // optional uint32 action_index = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_action_index());
    }
  }
   {
    // required .aasdk.proto.enums.TouchAction.Enum touch_action = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_touch_action());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TouchEvent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TouchEvent*>(&to_msg);
  auto& from = static_cast<const TouchEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aasdk.proto.data.TouchEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_touch_location()->MergeFrom(
      from._internal_touch_location());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.action_index_ = from._impl_.action_index_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.touch_action_ = from._impl_.touch_action_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TouchEvent::CopyFrom(const TouchEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aasdk.proto.data.TouchEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TouchEvent::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const TouchEvent&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_touch_location()))
    return false;
  return true;
}

void TouchEvent::InternalSwap(TouchEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.touch_location_.InternalSwap(&other->_impl_.touch_location_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.touch_action_)
      + sizeof(TouchEvent::_impl_.touch_action_)
      - PROTOBUF_FIELD_OFFSET(TouchEvent, _impl_.action_index_)>(
          reinterpret_cast<char*>(&_impl_.action_index_),
          reinterpret_cast<char*>(&other->_impl_.action_index_));
}

::google::protobuf::Metadata TouchEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace proto
}  // namespace aasdk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_TouchEventData_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
